export interface KaraokeEvent {
  id: string;
  dayOfWeek: string;
  eventName: string;
  venueName: string;
  address: string;
  city: string;
  state: string;
  neighborhood: string;
  crossStreet: string;
  phone: string;
  dj: string;
  startTime: string;
  endTime: string;
  notes: string;
  image: string | null;
  isPrivateRoom: boolean;
  bookingUrl: string | null;
}

export const DAY_ORDER = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
  "Bi-Monthly Sundays",
  "Private Room Karaoke",
] as const;

export const karaokeEvents: KaraokeEvent[] = [
  // ─── MONDAY ───
  {
    id: "fusion-east-monday",
    dayOfWeek: "Monday",
    eventName: "Superstar Karaoke",
    venueName: "Fusion East",
    address: "1179 Elton Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "East New York",
    crossStreet: "Vandalia Ave And Egan Street",
    phone: "718-975-5065",
    dj: "DJ Chris Ford",
    startTime: "6:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available, Free Shots For Singers",
    image: "/venues/fusion-east-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "footprints-cafe",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night",
    venueName: "Footprints Cafe",
    address: "5814 Clarendon Road",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Canarsie",
    crossStreet: "East 58th Street And Ralph Avenue",
    phone: "718-451-3181",
    dj: "KJ Anthony Ford",
    startTime: "7:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/footprints-cafe.png",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "saints-and-scholars",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night",
    venueName: "Saints & Scholars",
    address: "790 Mclean Avenue",
    city: "Yonkers",
    state: "New York",
    neighborhood: "",
    crossStreet: "Mc Collum Place And Aqueduct Avenue",
    phone: "914-457-5550",
    dj: "Brooklyn Bill",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available, Kitchen Closes At 9pm",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "1683-bar",
    dayOfWeek: "Monday",
    eventName: "Monday Night Karaoke",
    venueName: "1683 Bar & Restaurant",
    address: "401 Sunrise Highway",
    city: "West Islip",
    state: "New York",
    neighborhood: "",
    crossStreet: "",
    phone: "",
    dj: "Buddha's Killa Karaoke",
    startTime: "7:00 PM",
    endTime: "10:30 PM",
    notes: "Family Friendly, All Ages Welcomed, Kids Menu Available, Food & Drink Specials",
    image: "/venues/1683-bar.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "island-grill",
    dayOfWeek: "Monday",
    eventName: "Karaoke Mondays",
    venueName: "Island Grill Cafe",
    address: "5501 Glenwood Road",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "",
    crossStreet: "Corner of E 55th Street",
    phone: "",
    dj: "DJ Tyrone",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Try The Rum Punch, Bucket Of Beers Available, Kitchen Is Open",
    image: "/venues/island-grill.png",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "native-bk",
    dayOfWeek: "Monday",
    eventName: "Karaoke Monday",
    venueName: "Native",
    address: "911 Broadway",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "",
    crossStreet: "",
    phone: "718-747-8288",
    dj: "KJ Gregory Wilson",
    startTime: "7:00 PM",
    endTime: "",
    notes: "Food And Drinks Available",
    image: "/venues/native-bk.png",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "sunset-bar",
    dayOfWeek: "Monday",
    eventName: "Karaoke Monday's",
    venueName: "Sunset Bar & Restaurant",
    address: "106 W 1st Street",
    city: "Mt Vernon",
    state: "New York",
    neighborhood: "",
    crossStreet: "",
    phone: "",
    dj: "Jaime Hype & Tender Kay",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food On Sale By Chef Mel, Drink Specials Available",
    image: "/venues/sunset-bar.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "skinny-bar",
    dayOfWeek: "Monday",
    eventName: "Night Karaoke",
    venueName: "The Skinny Bar & Lounge",
    address: "174 Orchard Street",
    city: "New York",
    state: "New York",
    neighborhood: "Lower East Side",
    crossStreet: "",
    phone: "",
    dj: "KJ Troy Kellz",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Free Entry, Doors Open At 7pm, Drinks & Food Available",
    image: "/venues/skinny-bar.png",
    isPrivateRoom: false,
    bookingUrl: null,
  },

  // ─── TUESDAY ───
  {
    id: "pitch-flatbush",
    dayOfWeek: "Tuesday",
    eventName: "Superstar Karaoke",
    venueName: "Pitch",
    address: "774 Flatbush Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Flatbush",
    crossStreet: "Clarkson Ave And Lenox Road",
    phone: "718-313-3100",
    dj: "Various KJ's",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available, Free Shots For Singers",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "metropolitan-bar",
    dayOfWeek: "Tuesday",
    eventName: "Queeraoke",
    venueName: "Metropolitan Bar",
    address: "559 Lorimer Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "",
    crossStreet: "Metropolitan Ave And Devoe St",
    phone: "718-599-4444",
    dj: "Rotating DJ's",
    startTime: "",
    endTime: "",
    notes: "",
    image: "/venues/metropolitan-bar.png",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "waterfall-lounge",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Waterfall Lounge",
    address: "4703 Church Ave",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "East Flatbush",
    crossStreet: "Schenectady Ave And East 48th Street",
    phone: "347-365-9318",
    dj: "DJ Dennis",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "blu-seafood",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Blu Seafood Restaurant",
    address: "222-02 Merrick Blvd",
    city: "Queens",
    state: "New York",
    neighborhood: "",
    crossStreet: "",
    phone: "",
    dj: "DJ Les And Friends",
    startTime: "7:00 PM",
    endTime: "12:00 AM",
    notes: "Free Shots For Singers",
    image: "/venues/blu-seafood.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "harlem-nights",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Tuesdays",
    venueName: "Harlem Nights Bar",
    address: "2361 Adam Clayton Powell Jr Blvd",
    city: "New York",
    state: "New York",
    neighborhood: "Harlem",
    crossStreet: "",
    phone: "",
    dj: "Mo The Vet",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Karaoke Junkees",
    image: "/venues/harlem-nights.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "mos-bar",
    dayOfWeek: "Tuesday",
    eventName: "So Fresh, So Clean Karaoke",
    venueName: "Mo's Bar and Lounge",
    address: "80 Lafayette Ave",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "",
    crossStreet: "",
    phone: "",
    dj: "Lamont & Friends",
    startTime: "7:00 PM",
    endTime: "11:00 PM",
    notes: "Happy Hour Ends At 7pm, Arrive Early For Choice Seating, RSVP @lamontcarolina",
    image: "/venues/mos-bar.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "oval-sports-lounge",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "The Oval Sports Bar & Lounge",
    address: "Church Avenue & East 42nd Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "",
    crossStreet: "Church Avenue & East 42nd Street",
    phone: "",
    dj: "DJ Tye Tye",
    startTime: "8:00 PM",
    endTime: "2:00 AM",
    notes: "Drink's On You, Free All Night, 21+ Only",
    image: "/venues/oval-sports-lounge.png",
    isPrivateRoom: false,
    bookingUrl: null,
  },

  // ─── WEDNESDAY ───
  {
    id: "patrick-steakhouse",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Patrick Steakhouse",
    address: "227 Rogers Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Crown Heights",
    crossStreet: "Union Street And President Street",
    phone: "347-789-9976",
    dj: "DJ Ron Entertainment",
    startTime: "5:00 PM",
    endTime: "10:00 PM",
    notes: "Food And Drinks Available, Free Shots For 1st Time Singer, Extensive Song Library (80s, 90s, Top 40, And More!)",
    image: "/venues/patrick-steakhouse.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "poseidon",
    dayOfWeek: "Wednesday",
    eventName: "Happy Hour Karaoke",
    venueName: "Poseidon",
    address: "279 Flatbush Ave",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Prospect Heights",
    crossStreet: "St Mark's Ave And Prospect Place",
    phone: "347-365-7637",
    dj: "DJ M-Tunez",
    startTime: "7:00 PM",
    endTime: "2:00 AM",
    notes: "Happy Hour All Night",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "buck-it-sports",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Buck It Sports & Latin Grill",
    address: "1039 Surf Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Coney Island",
    crossStreet: "West 12th St & West 10th St",
    phone: "347-347-2157",
    dj: "DJ Oscar De La Paz",
    startTime: "7:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "my-place-tavern",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "My Place Tavern",
    address: "990 Middle Country Rd",
    city: "Selden",
    state: "New York",
    neighborhood: "Brookhaven",
    crossStreet: "Off Of College Road",
    phone: "631-846-9091",
    dj: "KJ Road Dog Tony",
    startTime: "7:30 PM",
    endTime: "11:30 PM",
    notes: "Every Song Gets A Spin On The Prize Wheel",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "gt-kingston",
    dayOfWeek: "Wednesday",
    eventName: "Open Mic Karaoke",
    venueName: "GT Kingston",
    address: "114-45 Lefferts Blvd",
    city: "Queens",
    state: "New York",
    neighborhood: "South Ozone Park",
    crossStreet: "Linden Blvd And 115th Ave",
    phone: "718-848-6006",
    dj: "DJ Denis",
    startTime: "8:00 PM",
    endTime: "4:00 AM",
    notes: "Free Fried Fish & Festival",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "lagos-times-square",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Lagos Times Square",
    address: "727 7th Avenue",
    city: "Manhattan",
    state: "New York",
    neighborhood: "Theater District",
    crossStreet: "West 48th Street And West 49th Street",
    phone: "212-281-0500",
    dj: "Various KJ's",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "ocho-rios",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Ocho Rios Seafood & Lounge",
    address: "1810 Flatbush Ave And Ave K",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "",
    crossStreet: "Ave K",
    phone: "",
    dj: "DJ Cindy & DJ Suppamixx",
    startTime: "9:00 PM",
    endTime: "",
    notes: "Bucket Beers 6 For $25, Food On The House",
    image: "/venues/ocho-rios.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
  },

  // ─── THURSDAY ───
  {
    id: "95-south",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "95 South",
    address: "778 Franklin Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Prospect Heights",
    crossStreet: "Lincoln Place And St Johns Place",
    phone: "347-750-6180",
    dj: "DJ Frank Smooth",
    startTime: "5:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available, Hookah Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "ocean-prime",
    dayOfWeek: "Thursday",
    eventName: "Open Acoustic Jam",
    venueName: "Ocean Prime",
    address: "64-14 Flushing Avenue",
    city: "Maspeth",
    state: "New York",
    neighborhood: "",
    crossStreet: "64th Street And 65th Street",
    phone: "718-326-3707",
    dj: "Dead Roses Productions",
    startTime: "6:00 PM",
    endTime: "10:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "murfs-tavern",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Murf's Backstreet Tavern",
    address: "64 Division Street",
    city: "Sag Harbor",
    state: "New York",
    neighborhood: "Southampton",
    crossStreet: "Rector Street And Cross Street",
    phone: "631-899-3575",
    dj: "KJ John Barrett",
    startTime: "6:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "samurai-lounge",
    dayOfWeek: "Thursday",
    eventName: "Kimono Karaoke",
    venueName: "The Samurai Lounge",
    address: "8812-14 4th Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Bay Ridge",
    crossStreet: "88th Street And 89th Street",
    phone: "718-808-6105",
    dj: "Kimono Karaoke",
    startTime: "6:30 PM",
    endTime: "Late",
    notes: "Food And Drinks Available, Free Sake Shot For First Time Singers",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "deja-vu",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Deja Vu Haitian Restaurant",
    address: "301 West 151 Street",
    city: "Harlem",
    state: "New York",
    neighborhood: "Central Harlem",
    crossStreet: "Bradhurst Avenue And Frederick Douglas Boulevard",
    phone: "718-737-3634",
    dj: "Queen Tashabee",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "prohibition",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Prohibition",
    address: "109 Front Street",
    city: "Massapequa Park",
    state: "New York",
    neighborhood: "",
    crossStreet: "7th Avenue And Park Boulevard",
    phone: "516-809-9223",
    dj: "DJ Brooke",
    startTime: "8:30 PM",
    endTime: "Late",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "noon-inn",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "The Noon Inn",
    address: "382A East Meadow Avenue",
    city: "East Meadow",
    state: "New York",
    neighborhood: "",
    crossStreet: "Prospect Ave And Franklin Ave",
    phone: "516-502-0803",
    dj: "Kara Okee",
    startTime: "8:30 PM",
    endTime: "12:30 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "curly-wolf",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Curly Wolf Saloon",
    address: "4116 Hylan Boulevard 2nd Floor",
    city: "Staten Island",
    state: "New York",
    neighborhood: "Great Kills",
    crossStreet: "Glover Street And Goodall Street",
    phone: "718-227-0027",
    dj: "DJ Frankie J",
    startTime: "9:00 PM",
    endTime: "12:00 AM",
    notes: "Liquid Courage Poured By Angela",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "rollin-greens",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Rollin Greens",
    address: "247-77 Jericho Turnpike",
    city: "Bellrose",
    state: "New York",
    neighborhood: "Floral Park",
    crossStreet: "Commonwealth Boulevard And 91st Avenue",
    phone: "718-343-3313",
    dj: "KJ Morgan",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "fusion-east-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Ladies Night",
    venueName: "Fusion East",
    address: "1179 Elton Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "East New York",
    crossStreet: "Vandalia Ave",
    phone: "718-975-5065",
    dj: "VJ Chris Forde",
    startTime: "6:00 PM",
    endTime: "11:00 PM",
    notes: "Free Shots For First Time Singers, Ladies Get Free Shots For Every Song",
    image: "/venues/fusion-east-thursday.png",
    isPrivateRoom: false,
    bookingUrl: null,
  },

  // ─── FRIDAY ───
  {
    id: "shannon-pot-2",
    dayOfWeek: "Friday",
    eventName: "Friday Night Karaoke",
    venueName: "Shannon Pot 2",
    address: "10-50 44th Drive",
    city: "Long Island City",
    state: "New York",
    neighborhood: "Hunters Point",
    crossStreet: "10th And 11th Street",
    phone: "917-396-1828",
    dj: "DJ Vince",
    startTime: "8:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "its-about-time",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "It's About Time Cocktail Lounge",
    address: "706 Main Street",
    city: "South Farmingdale",
    state: "New York",
    neighborhood: "",
    crossStreet: "Yoakum Ave And Fallwood Parkway",
    phone: "516-586-6690",
    dj: "KJ Road Dog Tony",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available, Rotating Specials",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "good-company",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "Good Company",
    address: "253-32 Northern Boulevard",
    city: "Queens",
    state: "New York",
    neighborhood: "Little Neck",
    crossStreet: "Westmoreland Street And Little Neck Parkway",
    phone: "718-428-0987",
    dj: "KJ Morgan",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "allans-bakery",
    dayOfWeek: "Friday",
    eventName: "Karaoke Friday's",
    venueName: "Allan's Bakery",
    address: "1107 Nostrand Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Prospect Lefferts Gardens",
    crossStreet: "Maple Street And Midwood Street",
    phone: "718-774-7892",
    dj: "Stress Therapy Karaoke Party",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "american-legion",
    dayOfWeek: "Friday",
    eventName: "Karaoke And Live Music",
    venueName: "American Legion Hall",
    address: "1130 East 92nd Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Canarsie",
    crossStreet: "Conklin Avenue And Glenwood Road",
    phone: "917-903-0334",
    dj: "Technic Music Mix",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "woodzy",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "Woodzy",
    address: "1133 Clarkson Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Brownsville",
    crossStreet: "Rockaway Parkway And East 96th Street",
    phone: "718-552-2687",
    dj: "DJ Hailes Costello",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "essence-bar",
    dayOfWeek: "Friday",
    eventName: "Superstar Karaoke",
    venueName: "Essence Bar & Grill",
    address: "1662 Atlantic Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Crown Heights",
    crossStreet: "Troy Avenue And Schenectady Avenue",
    phone: "718-467-3300",
    dj: "DJ Chris Ford",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/essence-bar.png",
    isPrivateRoom: false,
    bookingUrl: null,
  },

  // ─── SATURDAY ───
  {
    id: "la-cocina-boriqua",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Party",
    venueName: "La Cocina Boriqua",
    address: "2245 Westchester Avenue",
    city: "Bronx",
    state: "New York",
    neighborhood: "Belmont",
    crossStreet: "Glebe Avenue And Castle Hill Avenue",
    phone: "347-281-5375",
    dj: "DJ Nap",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Two Drink Minimum",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "whisky-reds",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Night",
    venueName: "Whisky Red's",
    address: "2552 Hempstead Turnpike",
    city: "East Meadow",
    state: "New York",
    neighborhood: "",
    crossStreet: "Taylor Avenue And Newbridge Road",
    phone: "516-605-0099",
    dj: "Kara Okee",
    startTime: "9:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "moonlight-pub",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Night",
    venueName: "Moonlight Pub",
    address: "247-77 Jericho Turnpike",
    city: "Bellrose",
    state: "New York",
    neighborhood: "",
    crossStreet: "Commonwealth Boulevard And 91st Avenue",
    phone: "718-343-3313",
    dj: "KJ Morgan",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "irish-american-pub",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Saturday",
    venueName: "Irish American Pub",
    address: "17 John Street",
    city: "Manhattan",
    state: "New York",
    neighborhood: "Financial District",
    crossStreet: "Nassau Street And Broadway",
    phone: "646-414-6223",
    dj: "DJ Sri",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "c-list-cocktail-bar",
    dayOfWeek: "Saturday",
    eventName: "Superstar Karaoke",
    venueName: "The C-List Cocktail Bar",
    address: "835 Franklin Ave",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "",
    crossStreet: "Union St",
    phone: "",
    dj: "VDJ Chris Forde",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/c-list-cocktail-bar.png",
    isPrivateRoom: false,
    bookingUrl: null,
  },

  // ─── SUNDAY ───
  {
    id: "333-lounge",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "333 Lounge And Restaurant",
    address: "333 Flatbush Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Prospect Heights",
    crossStreet: "Park Place And Prospect Place",
    phone: "718-399-8008",
    dj: "KJ Anthony Ford",
    startTime: "4:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },
  {
    id: "lilahs-bar",
    dayOfWeek: "Bi-Monthly Sundays",
    eventName: "Karaoke Night",
    venueName: "Lilah's Bar And Grill",
    address: "33 Main Street",
    city: "East Rockaway",
    state: "New York",
    neighborhood: "",
    crossStreet: "Cammerer Avenue And Front Street",
    phone: "516-284-7397",
    dj: "KJ Road Dog Tony",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
  },

  // ─── PRIVATE ROOM KARAOKE ───
  {
    id: "sing-sing-ave-a",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Sing Sing Karaoke",
    address: "81 Avenue A",
    city: "New York",
    state: "New York",
    neighborhood: "East Village",
    crossStreet: "East 5th & East 6th St",
    phone: "212-674-0700",
    dj: "Open",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
  },
  {
    id: "sing-sing-st-marks",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Sing Sing Karaoke",
    address: "9 St Marks Pl",
    city: "New York",
    state: "New York",
    neighborhood: "East Village",
    crossStreet: "2nd And 3rd Ave",
    phone: "212-387-7800",
    dj: "Open",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
  },
  {
    id: "boho-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Boho Karaoke",
    address: "West 4th",
    city: "New York",
    state: "New York",
    neighborhood: "West Village",
    crossStreet: "",
    phone: "",
    dj: "Open",
    startTime: "",
    endTime: "",
    notes: "",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
  },
];

// Group events by day
export function getEventsByDay(): Record<string, KaraokeEvent[]> {
  const grouped: Record<string, KaraokeEvent[]> = {};
  for (const day of DAY_ORDER) {
    grouped[day] = karaokeEvents.filter((e) => e.dayOfWeek === day);
  }
  return grouped;
}

// ─── BACKWARD-COMPATIBLE EXPORTS ───
// These keep the other pages (venue detail, map, search, etc.) working
// while we transition to the new event-based data model.

const placeholderImage = "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80";

export const venues = karaokeEvents.map((e) => ({
  id: e.id,
  name: e.venueName,
  neighborhood: e.neighborhood || `${e.city}, ${e.state}`,
  rating: 4.5,
  reviewCount: 0,
  priceRange: "$$",
  isLive: false,
  coverCharge: null,
  hasDrinkSpecials: e.notes.toLowerCase().includes("drink") || e.notes.toLowerCase().includes("happy hour"),
  image: e.image || placeholderImage,
  address: `${e.address}, ${e.city}, ${e.state}`,
  longitude: -73.99,
  latitude: 40.73,
  hours: {
    today: e.startTime && e.endTime ? `${e.startTime} - ${e.endTime}` : "Check venue",
    monThu: e.startTime && e.endTime ? `${e.startTime} - ${e.endTime}` : "Check venue",
    friSat: e.startTime && e.endTime ? `${e.startTime} - ${e.endTime}` : "Check venue",
    sun: e.startTime && e.endTime ? `${e.startTime} - ${e.endTime}` : "Check venue",
  },
  isOpen: true,
  specials: [] as { type: string; title: string; detail: string }[],
  recentlyPlayed: [] as { title: string; artist: string; timeAgo: string }[],
  isFavorite: false,
}));

export const events = [
  {
    id: "karaoke-friday",
    title: "Superstar Karaoke Friday",
    venue: "Essence Bar & Grill",
    date: "Every Friday",
    time: "9PM",
    image: "/venues/essence-bar.png",
  },
  {
    id: "queeraoke-tuesday",
    title: "Queeraoke Tuesdays",
    venue: "Metropolitan Bar",
    date: "Every Tuesday",
    time: "10PM",
    image: "/venues/metropolitan-bar.png",
  },
  {
    id: "ladies-night-thursday",
    title: "Karaoke Ladies Night",
    venue: "Fusion East",
    date: "Every Thursday",
    time: "6PM",
    image: "/venues/fusion-east-thursday.png",
  },
];

export const reviews = [
  {
    id: "r1",
    author: "Sarah Jenkins",
    rating: 5,
    timeAgo: "2d ago",
    text: "The sound system here is incredible. Best private rooms in the LES! Definitely coming back for my birthday.",
    avatar: null,
  },
  {
    id: "r2",
    author: "Mike Thompson",
    rating: 4,
    timeAgo: "1w ago",
    text: "Great song selection. The drinks are a bit pricey but worth it for the vibe.",
    avatar: null,
  },
];

export const songSearchResults = [
  {
    song: "Don't Stop Believin'",
    artist: "Journey",
    venues: [
      { name: "Fusion East", distance: "0.2 mi", neighborhood: "East New York", available: true, waitTime: null, special: "Free Shots For Singers" },
      { name: "Metropolitan Bar", distance: "0.8 mi", neighborhood: "Williamsburg", available: true, waitTime: "20m Waitlist", special: "Queeraoke Tuesdays" },
      { name: "Patrick Steakhouse", distance: "1.1 mi", neighborhood: "Crown Heights", available: true, waitTime: null, special: "Free Shots For 1st Time Singer" },
      { name: "Essence Bar & Grill", distance: "2.4 mi", neighborhood: "Crown Heights", available: false, waitTime: null, special: null },
    ],
  },
];

export const sponsoredKJ = {
  name: "DJ Chris Ford",
  venue: "Fusion East",
  time: "Tonight 6PM - 11PM",
  isTrending: true,
  image: "/venues/fusion-east-monday.jpg",
};

export const userProfile = {
  name: "Karaoke King NYC",
  username: "@alex_vocalist",
  isPremium: true,
  isKJVerified: true,
  venuesVisited: 42,
  reviewsCount: 128,
  followers: "1.2k",
  avatar: null,
  favorites: [
    { id: "fusion-east-monday", name: "Fusion East", neighborhood: "East New York", image: "/venues/fusion-east-monday.jpg" },
    { id: "essence-bar", name: "Essence Bar & Grill", neighborhood: "Crown Heights", image: "/venues/essence-bar.png" },
  ],
};
