export interface KaraokeEvent {
  id: string;
  dayOfWeek: string;
  eventName: string;
  venueName: string;
  address: string;
  city: string;
  state: string;
  zipCode?: string;
  neighborhood: string;
  crossStreet: string;
  phone: string;
  dj: string;
  startTime: string;
  endTime: string;
  notes: string;
  image: string | null;
  flyer?: string | null;
  isPrivateRoom: boolean;
  bookingUrl: string | null;
  website: string | null;
  latitude?: number | null;
  longitude?: number | null;
}

export const DAY_ORDER = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
  "Private Room Karaoke",
] as const;

// Map non-standard day names to their parent day for grouping
export const DAY_NORMALIZE: Record<string, string> = {
  // Plural forms
  "Mondays": "Monday",
  "Tuesdays": "Tuesday",
  "Wednesdays": "Wednesday",
  "Thursdays": "Thursday",
  "Fridays": "Friday",
  "Saturdays": "Saturday",
  "Sundays": "Sunday",
  // Non-standard recurring
  "Bi Monthly Sundays": "Sunday",
  "Bi-Monthly Sundays": "Sunday",
  "Every 3rd Monday": "Monday",
  "1st And 3rd Mondays": "Monday",
  "Every 1st And 3rd Saturdays": "Saturday",
  "Monthly Fridays": "Friday",
  "Open Karaoke Party Room": "Private Room Karaoke",
};

export const karaokeEvents: KaraokeEvent[] = [
  // ─── MONDAY ───
  {
    id: "fusion-east-monday",
    dayOfWeek: "Monday",
    eventName: "Superstar Karaoke",
    venueName: "Fusion East",
    address: "1179 Elton Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11239",
    neighborhood: "East New York",
    crossStreet: "Vandalia Ave And Egan Street",
    phone: "718-975-5065",
    dj: "DJ Chris Forde",
    startTime: "6:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available, Free Shots For Singers",
    image: "/venues/fusion-east-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "footprints-cafe-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night",
    venueName: "Footprints Cafe",
    address: "5814 Clarendon Road",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11203",
    neighborhood: "Canarsie",
    crossStreet: "East 58th Street And Ralph Avenue",
    phone: "718-451-3181",
    dj: "KJ Anthony Ford",
    startTime: "7:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/footprints-cafe.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "saints-scholars-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night",
    venueName: "Saints & Scholars",
    address: "790 Mclean Avenue",
    city: "Yonkers",
    state: "New York",
    zipCode: "10704",
    neighborhood: "Yonkers",
    crossStreet: "Mc Collum Place And Aqueduct Avenue",
    phone: "914-457-5550",
    dj: "Brooklyn Bill",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available, Kitchen Closes At 9pm",
    image: "/venues/saints-scholars-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "sunset-bar-and-restaurant-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Mondays",
    venueName: "Sunset Bar And Restaurant",
    address: "106 West 1st Street",
    city: "Mount Vernon",
    state: "New York",
    zipCode: "10550",
    neighborhood: "Mount Vernon",
    crossStreet: "South 9th Avenue And South 8th Avenue",
    phone: "914-230-0999",
    dj: "Ultra Karaoke",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "native-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night",
    venueName: "Native",
    address: "911 Broadway",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11206",
    neighborhood: "Bushwick",
    crossStreet: "Arion Place And Melrose St",
    phone: "718-747-8288",
    dj: "KJ Gregory Wilson",
    startTime: "6:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available, Kitchen Closes At 9pm",
    image: "/venues/native-bk.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "4807-church-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night Mondays",
    venueName: "4807 Church",
    address: "4807 Church Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11203",
    neighborhood: "East Flatbush",
    crossStreet: "East 48th Street and East 49th Street",
    phone: "N/A",
    dj: "Dj Les",
    startTime: "9:00 PM",
    endTime: "3:00 AM",
    notes: "Food And Drinks Available Sing Like A Star With Marcia P",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "gt-kingston-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night",
    venueName: "GT Kingston",
    address: "114-45 Lefferts Blvd",
    city: "Queens",
    state: "New York",
    zipCode: "11420",
    neighborhood: "South Ozone Park",
    crossStreet: "Linden Blvd And 115th Ave",
    phone: "718-848-6006",
    dj: "Dj Denis",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "island-grill-cafe-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Mondays",
    venueName: "Island Grill Cafe",
    address: "5501 Glenwood Road",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11234",
    neighborhood: "East Flatbush",
    crossStreet: "East 55th Street And East 56th Street",
    phone: "718-531-6281",
    dj: "Dj Tyrone",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Drinks Only",
    image: "/venues/island-grill.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "the-skinny-bar-and-lounge-monday",
    dayOfWeek: "Monday",
    eventName: "Night Karaoke",
    venueName: "The Skinny Bar And Lounge",
    address: "174 Orchard Street",
    city: "New York",
    state: "New York",
    zipCode: "10002",
    neighborhood: "Lower East Side",
    crossStreet: "Stanton Street And East Houston Street",
    phone: "212-228-3668",
    dj: "KJ Troy Kellz",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "1683-bar-restaurant-monday",
    dayOfWeek: "Monday",
    eventName: "Monday Night Karaoke",
    venueName: "1683 Bar & Restaurant",
    address: "401 Sunrise Highway",
    city: "West Islip",
    state: "New York",
    zipCode: "11795",
    neighborhood: "West Islip",
    crossStreet: "N/A",
    phone: "631-500-0650",
    dj: "Buddha Killa Karaoke",
    startTime: "7:00 PM",
    endTime: "10:30 PM",
    notes: "Food And Drinks Available",
    image: "/venues/1683-bar.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  // ─── TUESDAY ───
  {
    id: "pitch-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Pitch",
    address: "774 Flatbush Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11226",
    neighborhood: "Flatbush",
    crossStreet: "Clarkson Ave And Lenox Road",
    phone: "718-313-3100",
    dj: "Various KJ's",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available, Free Shots For Singers",
    image: "/venues/pitch-tuesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "alibi-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Tacos And Karaoke",
    venueName: "Alibi",
    address: "133-10 Cross Bay Blvd",
    city: "Queens",
    state: "New York",
    zipCode: "11417",
    neighborhood: "Ozone Park",
    crossStreet: "Doxsey Place And Silver Road",
    phone: "718-269-5077",
    dj: "Various KJ's",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "the-oval-sports-bar-and-lounge-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "The Oval Sports Bar And Lounge",
    address: "171 East 42nd Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11203",
    neighborhood: "East Flatbush",
    crossStreet: "Church Avenue And Linden Blvd",
    phone: "N/A",
    dj: "Dj Tye Tye",
    startTime: "8:00 PM",
    endTime: "2:00 AM",
    notes: "Drinks Only",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "drink-lounge-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Drink Lounge",
    address: "768 Franklin Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11238",
    neighborhood: "Crown Heights",
    crossStreet: "St John's Place And Lincoln Place",
    phone: "347-789-3833",
    dj: "Hosted By La La And Dj Ron",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Drinks Only",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "blu-seafood-restaurant-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Blu Seafood Restaurant",
    address: "222-02 Merrick Blvd",
    city: "Queens",
    state: "New York",
    zipCode: "11413",
    neighborhood: "Cambria Heights",
    crossStreet: "222nd Street And 223rd Street",
    phone: "929-600-5573",
    dj: "Dj Les",
    startTime: "7:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available, Free Shots For Singers",
    image: "/venues/blu-seafood.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "sandy-jacks-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Sandy Jacks",
    address: "683 5th Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11215",
    neighborhood: "Park Slope",
    crossStreet: "21st Street And 20th Street",
    phone: "347-889-6078",
    dj: "Kings Of Karaoke",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "richards-restaurant-and-grill-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Richards Restaurant And Grill",
    address: "5505 Church Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11203",
    neighborhood: "East Flatbush",
    crossStreet: "East 55th Street And East 56th Street",
    phone: "516-444-5507",
    dj: "Dj Styling",
    startTime: "9:00 PM",
    endTime: "3:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "echo-bravo-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Echo Bravo",
    address: "445 Troutman Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11237",
    neighborhood: "Bushwick",
    crossStreet: "Scott Avenue And Cypress Avenue",
    phone: "347-542-4117",
    dj: "Kings Of Karaoke",
    startTime: "9:30 PM",
    endTime: "12:30 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "edie-jo-s-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Edie Jo's",
    address: "630 Flatbush Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11225",
    neighborhood: "Prospect Lefferts Gardens",
    crossStreet: "Fenimore Street And Hawthorne Street",
    phone: "914-229-3300",
    dj: "Kings Of Karaoke",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "someplace-else-bar-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Industry Night",
    venueName: "Someplace Else Bar",
    address: "226 Higbee Lane",
    city: "West Islip",
    state: "New York",
    zipCode: "11795",
    neighborhood: "West Islip",
    crossStreet: "Carnation Road And West Islip Blvd",
    phone: "631-539-9777",
    dj: "Buddha Killa Karaoke",
    startTime: "10:30 PM",
    endTime: "1:30 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "lucky-13-saloon-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Lucky 13 Saloon",
    address: "644 Sackett St",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11217",
    neighborhood: "Gowanus",
    crossStreet: "3rd Ave And 4th Ave",
    phone: "718-596-0666",
    dj: "Kings Of Karaoke",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Drinks Only",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "wraptor-restaurant-bar-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Wraptor Restaurant Bar",
    address: "358 Columbia Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11231",
    neighborhood: "Columbia Street Waterfront District",
    crossStreet: "Seabring Street And Commerce Street",
    phone: "347-457-6333",
    dj: "Dj Amythest",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "flava-2-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Stress Therapy Karaoke Party",
    venueName: "Flava 2",
    address: "8920 Avenue D",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11236",
    neighborhood: "Canarsie",
    crossStreet: "Remsen And East 89th Street",
    phone: "718-975-8512",
    dj: "Stress Therapy Karaoke Party",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "metropolitan-bar-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Queeraoke",
    venueName: "Metropolitan Bar",
    address: "559 Lorimer Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11211",
    neighborhood: "Williamburg",
    crossStreet: "Metropolitan Ave And Devoe St",
    phone: "718-599-4444",
    dj: "Miss Katie",
    startTime: "10:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/metropolitan-bar.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "waterfall-lounge-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Waterfall Lounge",
    address: "4703 Church Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11203",
    neighborhood: "East Flatbush",
    crossStreet: "Schenectady Ave And East 48th Street",
    phone: "347-365-9318",
    dj: "DJ Dennis",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "barbablu-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Barbablu",
    address: "79 Grand Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11249",
    neighborhood: "Williamsburg",
    crossStreet: "Wythe Avenue And Berry Street",
    phone: "718-388-1999",
    dj: "Dj Plur",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "harlem-nights-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Tuesdays",
    venueName: "Harlem Nights",
    address: "2361 Adam Clayton Powell Junior Blvd",
    city: "Brooklyn",
    state: "New York",
    zipCode: "10030",
    neighborhood: "Harlem",
    crossStreet: "Odell Clark Place And West 139th Street",
    phone: "646-820-4603",
    dj: "Karaoke Junkies",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "mo-s-bar-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "So Fresh So Clean Karaoke",
    venueName: "Mo's Bar",
    address: "80 Lafayette Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11217",
    neighborhood: "Fort Greene",
    crossStreet: "South Portland Ave And South Elliott Place",
    phone: "N/A",
    dj: "Lamont & Friends",
    startTime: "7:00 PM",
    endTime: "11:00 PM",
    notes: "Drinks Only",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  // ─── WEDNESDAY ───
  {
    id: "patrick-steakhouse-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Patrick Steakhouse",
    address: "227 Rogers Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11225",
    neighborhood: "Crown Heights",
    crossStreet: "Union Street And President Street",
    phone: "347-789-9976",
    dj: "DJ Ron Entertainment",
    startTime: "5:00 PM",
    endTime: "10:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/patrick-steakhouse.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "hamilton-hall-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Hamilton Hall",
    address: "3493 Broadway",
    city: "New York",
    state: "New York",
    zipCode: "10031",
    neighborhood: "Hamilton Heights",
    crossStreet: "West 142nd And West 143rd Street",
    phone: "646-454-9797",
    dj: "Various KJ's",
    startTime: "9:30 PM",
    endTime: "1:00:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "royal-restaurant-2-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Royal Restaurant 2",
    address: "5419 Church Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11203",
    neighborhood: "East Flatbush",
    crossStreet: "East 55th Street And East 54th Street",
    phone: "N/A",
    dj: "Dj Tyrone",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "the-brew-house-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "The Brew House",
    address: "924 Hillside Ave",
    city: "New Hyde Park",
    state: "New York",
    zipCode: "11040",
    neighborhood: "New Hyde Park",
    crossStreet: "Franklin Ave And Lakeville Road",
    phone: "516-502-6740",
    dj: "Star Track Entertainment",
    startTime: "9:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "poseidon-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Happy Hour Karaoke",
    venueName: "Poseidon",
    address: "279 Flatbush Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11217",
    neighborhood: "Prospect Heights",
    crossStreet: "St Mark's Ave And Prosplect Place",
    phone: "347-365-7637",
    dj: "DJ M-Tunez",
    startTime: "7:00 PM",
    endTime: "2:00 AM",
    notes: "Happy Hour All Night",
    image: "/venues/poseidon-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "bamboo-walk-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Wednesdays",
    venueName: "Bamboo Walk",
    address: "1343 Utica Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11203",
    neighborhood: "East Flatbush",
    crossStreet: "Foster Ave And Farragut Road",
    phone: "718-369-0001",
    dj: "Hailes Costello",
    startTime: "7:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "havana-cafe-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Havana Cafe",
    address: "3151 East Tremont Ave",
    city: "Bronx",
    state: "New York",
    zipCode: "10461",
    neighborhood: "Pelham Bay",
    crossStreet: "La Salle Ave And Coddington Ave",
    phone: "718-518-1800",
    dj: "Dj Rizzo",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "matrix-lounge-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Matrix Lounge",
    address: "325 Lenox Ave",
    city: "Harlem",
    state: "New York",
    zipCode: "10027",
    neighborhood: "Harlem",
    crossStreet: "West 127th Street And West 126th Street",
    phone: "212-837-1469",
    dj: "The Alliance Dj's",
    startTime: "5:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "the-angry-gnome-pub-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "The Angry Gnome Pub",
    address: "1217 Jericho Turnpike",
    city: "New Hyde Park",
    state: "New York",
    zipCode: "11040",
    neighborhood: "",
    crossStreet: "",
    phone: "516-502-2224",
    dj: "KJ Morgan",
    startTime: "9:30 PM",
    endTime: "1:30 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "irish-american-pub-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Irish American Pub",
    address: "17 John Street",
    city: "New York",
    state: "New York",
    zipCode: "10038",
    neighborhood: "Financial District",
    crossStreet: "Nassau Street And Broadway",
    phone: "347-365-7637",
    dj: "DJ Plur",
    startTime: "6:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "havana-room-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Havana Room",
    address: "3604 East Tremont Avenue",
    city: "Bronx",
    state: "New York",
    zipCode: "10465",
    neighborhood: "Schuylerville, East Bronx",
    crossStreet: "Lafayette Avenue And Phillip Avenue",
    phone: "718-518-1800",
    dj: "Dj Opie",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "buck-it-sports-latin-grill-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Buck It Sports & Latin Grill",
    address: "1039 Surf Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11224",
    neighborhood: "Coney Island",
    crossStreet: "West 12th St & West 10th St",
    phone: "347-347-2157",
    dj: "DJ Oscar De La Paz",
    startTime: "7:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/buck-it-sports-latin-grill-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "my-place-tavern-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "My Place Tavern",
    address: "990 Middle Country Rd",
    city: "Selden",
    state: "New York",
    zipCode: "11784",
    neighborhood: "Brookhaven",
    crossStreet: "Off Of College Road",
    phone: "631-846-9091",
    dj: "KJ Road Dog Tony",
    startTime: "7:30 PM",
    endTime: "11:30 PM",
    notes: "Every Song Gets A Spin On The Prize Wheel",
    image: "/venues/my-place-tavern-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "american-cheez-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "American Cheez",
    address: "444 7th Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11215",
    neighborhood: "Park Slope",
    crossStreet: "15th Street And 16th Street",
    phone: "347-725-4665",
    dj: "Kings Of Karaoke",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "talon-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Talon",
    address: "220 Wyckoff Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11237",
    neighborhood: "Bushwick",
    crossStreet: "Bleeker Street And Menahan Street",
    phone: "N/A",
    dj: "Kings Of Karaoke",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Drinks Only",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "gt-kingston-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Open Mic Karaoke",
    venueName: "GT Kingston",
    address: "114-45 Lefferts Blvd",
    city: "Queens",
    state: "New York",
    zipCode: "11420",
    neighborhood: "South Ozone Park",
    crossStreet: "Linden Blvd And 115th Ave",
    phone: "718-848-6006",
    dj: "Dj Denis",
    startTime: "8:00 PM",
    endTime: "4:00 AM",
    notes: "Free Fried Fish & Festival",
    image: "/venues/gt-kingston-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "lagos-times-square-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Lagos Times Square",
    address: "727 7th Avenue",
    city: "Manhattan",
    state: "New York",
    zipCode: "10019",
    neighborhood: "Theater District",
    crossStreet: "West 48th Street And West 49th Street",
    phone: "212-281-0500",
    dj: "Various KJ's",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/lagos-times-square-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "mc-shane-s-pub-restaurant-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Mc Shane's Pub & Restaurant",
    address: "123 N Main St",
    city: "Port Chester",
    state: "New York",
    zipCode: "10573",
    neighborhood: "Port Chester",
    crossStreet: "Adee  St And Willett Ave",
    phone: "914-937-7800",
    dj: "Brooklyn Bill",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/mc-shane-s-pub-restaurant-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "alligator-lounge-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Alligator Lounge",
    address: "600 Metropolitan Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11211",
    neighborhood: "Williamsburg",
    crossStreet: "Lorimer Street And Leonard Street",
    phone: "718-599-4440",
    dj: "Various Kj's",
    startTime: "11:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "canz-bohemia-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Wednesday Karaoke Night",
    venueName: "Canz Bohemia",
    address: "4780 Sunrise Highway",
    city: "Bohemia",
    state: "New York",
    zipCode: "11716",
    neighborhood: "Bohemia",
    crossStreet: "Smithtown Ave And Walnut Ave",
    phone: "631-256-5575",
    dj: "Buddha Killa Karaoke",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "brixx-bar-and-grill-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Brixx Bar And Grill",
    address: "2819 North Jerusalem Road",
    city: "East Meadow",
    state: "New York",
    zipCode: "11554",
    neighborhood: "East Meadow",
    crossStreet: "Bellmore Road And Marion Drive",
    phone: "516-804-9954",
    dj: "Kara Okee",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  // ─── THURSDAY ───
  {
    id: "ocean-prime-thursday",
    dayOfWeek: "Thursday",
    eventName: "Open Acoustic Jam",
    venueName: "Ocean Prime",
    address: "64-14 Flushing Avenue",
    city: "Maspeth",
    state: "New York",
    zipCode: "11378",
    neighborhood: "Maspeth",
    crossStreet: "64th Street And 65th Street",
    phone: "718-326-3707",
    dj: "Dead Roses Productions",
    startTime: "6:00 PM",
    endTime: "10:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/ocean-prime-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "hamilton-hall-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Hamilton Hall",
    address: "3493 Broadway",
    city: "New York",
    state: "New York",
    zipCode: "10031",
    neighborhood: "Hamilton Heights",
    crossStreet: "West 142nd And West 143rd Street",
    phone: "646-454-9797",
    dj: "Various KJ's",
    startTime: "9:30 PM",
    endTime: "1:00:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "fusion-east-thursday",
    dayOfWeek: "Thursday",
    eventName: "Superstar Karaoke/LadiesNight",
    venueName: "Fusion East",
    address: "1179 Elton St",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11239",
    neighborhood: "East New York",
    crossStreet: "Vandalia Ave And Egan Street",
    phone: "718-326-3707",
    dj: "Dj Chris Forde",
    startTime: "6:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available, Free Shots For Singers, Ladies Free Shot Everytime They Sing",
    image: "/venues/fusion-east-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "the-throwback-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Thursdays",
    venueName: "The Throwback",
    address: "710 Amsterdam Avenue",
    city: "New York",
    state: "New York",
    zipCode: "10025",
    neighborhood: "Upper West Side",
    crossStreet: "West 94th Street And West 95th Street",
    phone: "N/A",
    dj: "Kings Of Karaoke",
    startTime: "7:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "alligator-lounge-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Alligator Lounge",
    address: "600 Metropolitan Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11211",
    neighborhood: "Williamsburg",
    crossStreet: "Lorimer Street And Leonard Street",
    phone: "718-599-4440",
    dj: "Various Kj's",
    startTime: "11:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "mr-nancy-s-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Thursdays",
    venueName: "Mr Nancy's",
    address: "702 Seneca Ave",
    city: "Queens",
    state: "New York",
    zipCode: "11385",
    neighborhood: "Ridgewood",
    crossStreet: "Palmetto Street And Woodbine Street",
    phone: "347-578-2647",
    dj: "Kings Of Karaoke",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "insa-thursday",
    dayOfWeek: "Thursday",
    eventName: "Open Mic Karaoke",
    venueName: "Insa",
    address: "328 Douglass Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11217",
    neighborhood: "Boerum Hill",
    crossStreet: "3rd Ave And 4th Avenue",
    phone: "718-855-2620",
    dj: "House Dj's",
    startTime: "8:30 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "merv-s-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Merv's",
    address: "266 Irving Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11237",
    neighborhood: "Bushwick",
    crossStreet: "Menahan Ave And Bleecker Street",
    phone: "347-715-4255",
    dj: "Kings Of Karaoke",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "irish-american-pub-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Irish American Pub",
    address: "17 John Street",
    city: "New York",
    state: "New York",
    zipCode: "10038",
    neighborhood: "Financial District",
    crossStreet: "Nassau Street And Broadway",
    phone: "347-365-7637",
    dj: "DJ Plur",
    startTime: "6:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "arirang-hibachi-steakhouse-thursday",
    dayOfWeek: "Thursday",
    eventName: "Kimono Karaoke",
    venueName: "Arirang Hibachi Steakhouse",
    address: "8812-14 4th Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11209",
    neighborhood: "Bay Ridge",
    crossStreet: "88th Street And 89th Street",
    phone: "718-808-6105",
    dj: "Kimono Karaoke",
    startTime: "6:30 PM",
    endTime: "Late",
    notes: "Food And Drinks Available, Free Sake Shot For First Time Singers",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "prohibition-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Prohibition",
    address: "109 Front Street",
    city: "Massapequa Park",
    state: "New York",
    zipCode: "11762",
    neighborhood: "Massapequa Park",
    crossStreet: "7th Avenue And Park Boulevard",
    phone: "516-809-9223",
    dj: "Dj Brooke",
    startTime: "8:30 PM",
    endTime: "Late",
    notes: "Food And Drinks Available",
    image: "/venues/prohibition-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "curly-wolf-saloon-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Curly Wolf Saloon",
    address: "4116 Hylan Boulevard 2nd Floor",
    city: "Staten Island",
    state: "New York",
    zipCode: "10308",
    neighborhood: "Great Kills",
    crossStreet: "Glover Street And Goodall Street",
    phone: "718-227-0027",
    dj: "Dj Frankie J",
    startTime: "9:00 PM",
    endTime: "12:00 AM",
    notes: "Liquid Courage Poured By Angela",
    image: "/venues/curly-wolf-saloon-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "pitants-sports-bar-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Pitants Sports Bar",
    address: "502 East 95th Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11212",
    neighborhood: "Brownsville",
    crossStreet: "Church Ave And Willmohr Street",
    phone: "N/A",
    dj: "Stress Therapy Karaoke Party",
    startTime: "10:00 PM",
    endTime: "3:00 AM",
    notes: "Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "island-suite-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Island Suite",
    address: "4112 Avenue D",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11203",
    neighborhood: "East Flatbush",
    crossStreet: "Albany And East 42nd Street",
    phone: "N/A",
    dj: "DJ Les",
    startTime: "10:00 PM",
    endTime: "3:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  // ─── FRIDAY ───
  {
    id: "shannon-pot-2-friday",
    dayOfWeek: "Friday",
    eventName: "Friday Night Karaoke",
    venueName: "Shannon Pot 2",
    address: "10-50 44th Drive",
    city: "Long Island City",
    state: "New York",
    zipCode: "11101",
    neighborhood: "Hunters Point",
    crossStreet: "10th And 11th Street",
    phone: "917-396-1828",
    dj: "DJ Vince",
    startTime: "8:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/shannon-pot-2-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "ocean-prime-friday",
    dayOfWeek: "Friday",
    eventName: "Friday Night Karaoke",
    venueName: "Ocean Prime",
    address: "64-14 Flushing Ave",
    city: "Maspeth",
    state: "New York",
    zipCode: "11378",
    neighborhood: "Maspeth",
    crossStreet: "64th And 65th Street",
    phone: "718-326-3707",
    dj: "Karaoke Chris",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "it-s-about-time-cocktail-lounge-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "It's About Time Cocktail Lounge",
    address: "706 Main Street",
    city: "South Farmingdale",
    state: "New York",
    zipCode: "11735",
    neighborhood: "South Farmingdale",
    crossStreet: "Yoakum Ave And Fallwood Parkway",
    phone: "516-586-6690",
    dj: "KJ Road Dog Tony",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available, Rotating Specials",
    image: "/venues/it-s-about-time-cocktail-lounge-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "brooklyn-chop-house-times-square-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Me Please",
    venueName: "Brooklyn Chop House Times Square",
    address: "253 West 47th Street",
    city: "New York",
    state: "New York",
    zipCode: "10036",
    neighborhood: "Times Square",
    crossStreet: "8th Avenue And Broadway",
    phone: "212 619-1210",
    dj: "Karaoke Me Please NYC",
    startTime: "10:00:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "good-company-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "Good Company",
    address: "253-32 Northern Boulevard",
    city: "Queens",
    state: "New York",
    zipCode: "11362",
    neighborhood: "Little Neck",
    crossStreet: "Westmoreland Street And Little Neck Parkway",
    phone: "718-428-0987",
    dj: "KJ Morgan",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/good-company-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "allan-s-bakery-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Friday's",
    venueName: "Allan's Bakery",
    address: "1107 Nostrand Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11225",
    neighborhood: "Prospect Lefferts Gardens",
    crossStreet: "Maple Street And Midwood Street",
    phone: "718-774-7892",
    dj: "Stress Therapy Karaoke Party",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/allan-s-bakery-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "american-legion-hall-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke And Live Music",
    venueName: "American Legion Hall",
    address: "1130 East 92nd Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11236",
    neighborhood: "Canarsie",
    crossStreet: "Conklin Avenue And Glenwood Road",
    phone: "917-903-0334",
    dj: "Technic Music Mix",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/american-legion-hall-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "woodzy-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "Woodzy",
    address: "1133 Clarkson Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11212",
    neighborhood: "Brownsville",
    crossStreet: "Rockaway Parkway And East 96th Street",
    phone: "718-552-2687",
    dj: "DJ Hailes Costello",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/woodzy-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "essence-bar-grill-friday",
    dayOfWeek: "Friday",
    eventName: "Superstar Karaoke",
    venueName: "Essence Bar & Grill",
    address: "1662 Atlantic Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11213",
    neighborhood: "Crown Heights",
    crossStreet: "Troy Avenue And Schnectady Avenue",
    phone: "718-467-3300",
    dj: "DJ Chris Forde",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available, Free Shot For Singers",
    image: "/venues/essence-bar.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "irish-american-pub-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "Irish American Pub",
    address: "17 John Street",
    city: "New York",
    state: "New York",
    zipCode: "10038",
    neighborhood: "Financial District",
    crossStreet: "Nassau Street And Broadway",
    phone: "347-365-7637",
    dj: "DJ Plur",
    startTime: "6:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "the-cobra-club-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "The Cobra Club",
    address: "6 Wyckoff Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11237",
    neighborhood: "Bushwick",
    crossStreet: "Jefferson Street And Troutman Street",
    phone: "718-418-1138",
    dj: "Kings OF Karaoke",
    startTime: "11:00 PM",
    endTime: "3:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "lvsiadas-restaurant-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "Lvsiadas Restaurant",
    address: "6 Roosevelt Square West",
    city: "Mount Vernon",
    state: "New York",
    zipCode: "10550",
    neighborhood: "Mount Vernon",
    crossStreet: "West Prospect Ave And Stevens Avenue",
    phone: "914-664-2131",
    dj: "Dj Theo",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available, Drink Specials All Night Long!",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "instant-reply-sports-bar-friday",
    dayOfWeek: "Friday",
    eventName: "Friday Night Karaoke",
    venueName: "Instant Reply Sports Bar",
    address: "282 East Jericho Turnpike",
    city: "Huntington Station",
    state: "New York",
    zipCode: "11746",
    neighborhood: "South Huntington",
    crossStreet: "Goeller Ave & Barkers Lane",
    phone: "631-673-6161",
    dj: "DJ Rizzo",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  // ─── SATURDAY ───
  {
    id: "la-cocina-boriqua-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Party",
    venueName: "La Cocina Boriqua",
    address: "2245 Westchester Avenue",
    city: "Bronx",
    state: "New York",
    zipCode: "10462",
    neighborhood: "Belmont",
    crossStreet: "Glebe Avenue And Castle Hill Avenue",
    phone: "347-281-5375",
    dj: "DJ Nap",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Two Drink Minimum",
    image: "/venues/la-cocina-boriqua-saturday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "montero-s-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Night",
    venueName: "Montero's",
    address: "73 Atlantic Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11201",
    neighborhood: "Brooklyn Heights",
    crossStreet: "Hicks Street And BQE",
    phone: "646-729-4129",
    dj: "Dj Amythest",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Drinks Only",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "whisky-red-s-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Night",
    venueName: "Whisky Red's",
    address: "2552 Hempstead Turnpike",
    city: "East Meadow",
    state: "New York",
    zipCode: "11554",
    neighborhood: "East Meadow",
    crossStreet: "Taylor Avenue And Newbridge Road",
    phone: "516-605-0099",
    dj: "Kara Okee",
    startTime: "9:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/whisky-red-s-saturday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "moonlight-pub-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Night",
    venueName: "Moonlight Pub",
    address: "247-77 Jericho Turnpike",
    city: "Bellrose",
    state: "New York",
    zipCode: "11001",
    neighborhood: "Bellrose",
    crossStreet: "Commonwealth Boulevard And 91st Avenue",
    phone: "718-343-3313",
    dj: "KJ Morgan",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/moonlight-pub-saturday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "irish-american-pub-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Saturday",
    venueName: "Irish American Pub",
    address: "17 John Street",
    city: "Manhattan",
    state: "New York",
    zipCode: "10038",
    neighborhood: "Financial District",
    crossStreet: "Nassau Street And Broadway",
    phone: "646-414-6223",
    dj: "DJ Sri",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/irish-american-pub-saturday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "the-brew-house-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Night",
    venueName: "The Brew House",
    address: "924 Hillside Ave",
    city: "New Hyde Park",
    state: "New York",
    zipCode: "11040",
    neighborhood: "New Hyde Park",
    crossStreet: "Franklin Ave And Lakeville Road",
    phone: "516-502-6740",
    dj: "Star Track Entertainment",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "the-cobra-club-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Night",
    venueName: "The Cobra Club",
    address: "6 Wyckoff Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11237",
    neighborhood: "Bushwick",
    crossStreet: "Jefferson Street And Troutman Street",
    phone: "718-418-1138",
    dj: "Kings OF Karaoke",
    startTime: "11:00 PM",
    endTime: "3:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  // ─── SUNDAY ───
  {
    id: "333-lounge-and-restaurant-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "333 Lounge And Restaurant",
    address: "333 Flatbush Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11217",
    neighborhood: "Prospect Heights",
    crossStreet: "Park Place And Prospect Place",
    phone: "718-399-8008",
    dj: "KJ Anthony Ford",
    startTime: "4:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/333-lounge-and-restaurant-sunday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "stop-at-the-spot-sunday",
    dayOfWeek: "Sunday",
    eventName: "Ultra Karaoke Sundays",
    venueName: "Stop At The Spot",
    address: "918 East 233 Street",
    city: "Bronx",
    state: "New York",
    zipCode: "10466",
    neighborhood: "Wakefield",
    crossStreet: "Bronxwood Ave And Paulding Avenue",
    phone: "929-285-3128",
    dj: "Ultra Karaoke",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "the-backyard-sunday",
    dayOfWeek: "Sunday",
    eventName: "Sunday Funday Karaoke",
    venueName: "The Backyard",
    address: "1241 Middle Country Road",
    city: "Middle Island",
    state: "New York",
    zipCode: "11953",
    neighborhood: "Middle Island",
    crossStreet: "N/A",
    phone: "631-380-1445",
    dj: "Dj Eric",
    startTime: "3:00 PM",
    endTime: "6:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "pitants-sports-bar-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "Pitants Sports Bar",
    address: "502 East 95th Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11212",
    neighborhood: "Brownsville",
    crossStreet: "Church Ave And Willmohr Street",
    phone: "N/A",
    dj: "Dj Denis",
    startTime: "10:00:00 PM",
    endTime: "3:00 AM",
    notes: "Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "la-mode-bk-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "La Mode BK",
    address: "1401 Bedford Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11216",
    neighborhood: "Crown Heights",
    crossStreet: "Prospect Place And St Marks Ave",
    phone: "718-316-9100",
    dj: "DJ Hailes Costello",
    startTime: "2:00 PM",
    endTime: "6:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "the-coal-pot-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "The Coal Pot",
    address: "1466 St John's Place",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11213",
    neighborhood: "Crown Heights",
    crossStreet: "Utica Ave And Rochester Ave",
    phone: "347-404-7705",
    dj: "Stress Therapy Karaoke Party",
    startTime: "7:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "midwood-flats-sunday",
    dayOfWeek: "Sunday",
    eventName: "Drag Queen Karaoke",
    venueName: "Midwood Flats",
    address: "577 Flatbush Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11226",
    neighborhood: "East Flatbush",
    crossStreet: "Midwood Street And Maple Street",
    phone: "347-404-7705",
    dj: "Miss Behave",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "rullo-s-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "Rullo's",
    address: "560 5th Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11215",
    neighborhood: "Park Slope",
    crossStreet: "16th Street And 15th Street",
    phone: "718-369-0077",
    dj: "Kings Of Karaoke",
    startTime: "8:30 PM",
    endTime: "12:30 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "frontline-bar-and-lounge-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "Frontline Bar And Lounge",
    address: "765 Utica Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11203",
    neighborhood: "East Flatbush",
    crossStreet: "Lenox Road And Linden Blvd",
    phone: "N/A",
    dj: "Dj Cindy And Dj Supamixx",
    startTime: "10:00 PM",
    endTime: "3:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "my-place-tavern-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "My Place Tavern",
    address: "990 Middle County Road",
    city: "Selden",
    state: "New York",
    zipCode: "11784",
    neighborhood: "Brookhaven",
    crossStreet: "Off Of College Road",
    phone: "631-846-9091",
    dj: "Road Dog Karaoke",
    startTime: "7:30 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  {
    id: "cassette-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "Cassette",
    address: "68-38 Forest Ave",
    city: "Flushing",
    state: "New York",
    zipCode: "11385",
    neighborhood: "Flushing",
    crossStreet: "Catalpa  Ave And 68th Road",
    phone: "917-966-6078",
    dj: "Kings Of Karaoke",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  // ─── BI MONTHLY SUNDAYS ───
  {
    id: "lilah-s-bar-and-grill-bi-monthly-sundays",
    dayOfWeek: "Bi Monthly Sundays",
    eventName: "Karaoke Night",
    venueName: "Lilah's Bar And Grill",
    address: "33 Main Street",
    city: "East Rockaway",
    state: "New York",
    zipCode: "11518",
    neighborhood: "East Rockaway",
    crossStreet: "Cammerer Avenue And Front Street",
    phone: "516-284-7397",
    dj: "KJ Road Dog Tony",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/lilah-s-bar-and-grill-bi-monthly-sundays.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  // ─── EVERY 3RD MONDAY ───
  {
    id: "whoopsie-daisy-bar-every-3rd-monday",
    dayOfWeek: "Every 3rd Monday",
    eventName: "Kickback Karaoke",
    venueName: "Whoopsie Daisy Bar",
    address: "225 Rogers Avenue",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11225",
    neighborhood: "Crown Heights",
    crossStreet: "Union Street And President Street",
    phone: "347-365-4193",
    dj: "Miss Behave",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  // ─── 1ST AND 3RD MONDAYS ───
  {
    id: "the-cobra-club-1st-and-3rd-mondays",
    dayOfWeek: "1st And 3rd Mondays",
    eventName: "80's And 90's Karaoke",
    venueName: "The Cobra Club",
    address: "6 Wyckoff Ave",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11237",
    neighborhood: "Bushwick",
    crossStreet: "Jefferson Street And Troutman Street",
    phone: "718-418-1138",
    dj: "Kings OF Karaoke",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
  },
  // ─── PRIVATE ROOM KARAOKE ───
  {
    id: "sing-sing-karaoke-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Sing Sing Karaoke",
    address: "81 Avenue A",
    city: "New York",
    state: "New York",
    zipCode: "10009",
    neighborhood: "East Village",
    crossStreet: "East 5th & East 6th St",
    phone: "212-674-0700",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/sing-sing-avenue-a.jpg",
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "sing-sing-karaoke-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Sing Sing Karaoke",
    address: "9 St Marks Place",
    city: "New York",
    state: "New York",
    zipCode: "10003",
    neighborhood: "West Village",
    crossStreet: "2nd And 3rd Ave",
    phone: "212-387-7800",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/sing-sing-avenue-a.jpg",
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "boho-karaoke-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Boho Karaoke",
    address: "186 West 4th Street",
    city: "New York",
    state: "New York",
    zipCode: "10014",
    neighborhood: "Washington Square Village",
    crossStreet: "Barrow St And Jones Street",
    phone: "212-255-0011",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "4:00 PM",
    endTime: "4:00 AM",
    notes: "Food And Drinks Availiable",
    image: "/venues/boho-karaoke.jpg",
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "boho-karaoke-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Boho Karaoke",
    address: "152 Orchard Street",
    city: "New York",
    state: "New York",
    zipCode: "10002",
    neighborhood: "China Town",
    crossStreet: "Rivington And Stanton Street",
    phone: "212-777-0102",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "4:00 PM",
    endTime: "4:00 AM",
    notes: "Food And Drinks Availiable",
    image: "/venues/boho-karaoke.jpg",
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "aux-karaoke-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Aux Karaoke",
    address: "2142 Fulton Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11233",
    neighborhood: "Bedstuy",
    crossStreet: "Rockaway Avenue And Thomas S Boyland Street",
    phone: "718-218-3348",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "5:00 PM",
    endTime: "12:00 AM",
    notes: "Drinks Only",
    image: "/venues/aux-karaoke.jpg",
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "anytime-karaoke-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Anytime Karaoke",
    address: "23 W 32nd Street",
    city: "New York",
    state: "New York",
    zipCode: "10001",
    neighborhood: "Koreatown",
    crossStreet: "5th And 6th Avenue",
    phone: "646-590-4703",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "5:00 PM",
    endTime: "3:00 AM",
    notes: "Food And Drinks Availiable",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "rpm-underground-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "RPM Underground",
    address: "246 W 54th Street",
    city: "New York",
    state: "New York",
    zipCode: "10019",
    neighborhood: "Midtown",
    crossStreet: "8th Avenue And Broadway",
    phone: "",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Availiable, Till 4am On Fridays And Saturdays",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "ms-kims-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Ms Kims",
    address: "6 West 28th Street Floor 2",
    city: "New York",
    state: "New York",
    zipCode: "10001",
    neighborhood: "Nomad (North Of MAdison Square Park)",
    crossStreet: "Broadway And 5th Avenue",
    phone: "929-505-3368",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "6:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Availiable, Till 2am On Fridays And Saturdays",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "karaoke-shout-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Karaoke Shout",
    address: "32-46 Steinway Street",
    city: "Astoria",
    state: "New York",
    zipCode: "11103",
    neighborhood: "Astoria",
    crossStreet: "Broadway And 34th Avenue",
    phone: "718-569-0080",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "5:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Availiable, Till 4am On Fridays And Saturdays",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "233-starr-karaoke-and-eats-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "233 Starr Karaoke And Eats",
    address: "233 Starr Street",
    city: "Brooklyn",
    state: "New York",
    zipCode: "11237",
    neighborhood: "Bushwick",
    crossStreet: "Wyckoff Ave And Irving Ave",
    phone: "929-210-8687",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "4:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Availiable, Till 2am On Fridays And Saturdays",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "singsing-karaoke-bar-and-chicken-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "SingSing Karaoke Bar And Chicken",
    address: "25-30 Broadway",
    city: "Astoria",
    state: "New York",
    zipCode: "11106",
    neighborhood: "Astoria",
    crossStreet: "Crescent And 29th Street",
    phone: "929-210-8687",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "4:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Availiable, Till 2am On Fridays And Saturdays",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
  {
    id: "101-ktv-bar-lounge-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "101 KTV Bar Lounge",
    address: "135-25 Northern Boulevard",
    city: "Flushing",
    state: "New York",
    zipCode: "11354",
    neighborhood: "Flushing",
    crossStreet: "Prince Street And Farrington Street",
    phone: "929-520-1011",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "2:00 PM",
    endTime: "4:00 AM",
    notes: "Food And Drinks Availiable",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: null,
  },
];

// Helper: get events grouped by day, or for a specific day
export function getEventsByDay(): Record<string, KaraokeEvent[]>;
export function getEventsByDay(day: string): KaraokeEvent[];
export function getEventsByDay(day?: string): Record<string, KaraokeEvent[]> | KaraokeEvent[] {
  if (day) return karaokeEvents.filter((e) => e.dayOfWeek === day);
  const grouped: Record<string, KaraokeEvent[]> = {};
  for (const event of karaokeEvents) {
    if (!grouped[event.dayOfWeek]) grouped[event.dayOfWeek] = [];
    grouped[event.dayOfWeek].push(event);
  }
  return grouped;
}

// Helper: venues derived from events (unique by name)
import { getVenueCoordinates } from "./venue-coordinates";

export const venues = karaokeEvents.reduce<
  Array<{
    id: string;
    name: string;
    address: string;
    neighborhood: string;
    city: string;
    state: string;
    image: string | null;
    isPrivateRoom: boolean;
    latitude: number | null;
    longitude: number | null;
  }>
>((acc, event) => {
  if (!acc.find((v) => v.name === event.venueName)) {
    const coords = getVenueCoordinates(event.address);
    acc.push({
      id: event.id,
      name: event.venueName,
      address: event.address,
      neighborhood: event.neighborhood,
      city: event.city,
      state: event.state,
      image: event.image,
      isPrivateRoom: event.isPrivateRoom,
      latitude: coords?.lat ?? null,
      longitude: coords?.lng ?? null,
    });
  }
  return acc;
}, []);

// Placeholder reviews (to be replaced by Supabase)
export const reviews: Array<{
  id: string;
  venueId: string;
  userName: string;
  rating: number;
  text: string;
  date: string;
}> = [];

// Song search demo data (used by /search page)
export const songSearchResults = [
  {
    song: "Don't Stop Believin'",
    artist: "Journey",
    venues: [
      { name: "Sing Sing Karaoke", distance: "0.3 mi", available: true, waitTime: "~15 min wait", special: "Happy Hour till 8 PM" },
      { name: "Boho Karaoke", distance: "0.5 mi", available: true, waitTime: null, special: null },
      { name: "Aux Karaoke", distance: "1.2 mi", available: false, waitTime: null, special: "2-for-1 Drinks" },
    ],
  },
];

// ─── KJ Profiles (derived from events) ───

export interface KJProfile {
  name: string;
  slug: string;
  venueCount: number;
  events: Array<{
    venueId: string;
    venueName: string;
    eventName: string;
    dayOfWeek: string;
    startTime: string;
    endTime: string;
    image: string | null;
    neighborhood: string;
    city: string;
  }>;
}

const EXCLUDED_KJ_NAMES = new Set([
  "", "n/a", "various kj's", "various kj's", "house dj's",
  "private rooms and open karaoke bar", "open",
]);

function generateKJSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function buildKJProfiles(): KJProfile[] {
  const kjMap = new Map<string, KJProfile>();

  for (const event of karaokeEvents) {
    const kjName = event.dj.trim();
    if (!kjName || EXCLUDED_KJ_NAMES.has(kjName.toLowerCase())) continue;

    const slug = generateKJSlug(kjName);
    if (!slug) continue;

    if (!kjMap.has(slug)) {
      kjMap.set(slug, { name: kjName, slug, venueCount: 0, events: [] });
    }

    kjMap.get(slug)!.events.push({
      venueId: event.id,
      venueName: event.venueName,
      eventName: event.eventName,
      dayOfWeek: event.dayOfWeek,
      startTime: event.startTime,
      endTime: event.endTime,
      image: event.image,
      neighborhood: event.neighborhood,
      city: event.city,
    });
  }

  for (const profile of kjMap.values()) {
    profile.venueCount = new Set(profile.events.map((e) => e.venueName)).size;
  }

  return Array.from(kjMap.values());
}

const kjProfiles = buildKJProfiles();
export const kjs = kjProfiles;
const kjBySlug = new Map(kjProfiles.map((kj) => [kj.slug, kj]));
const kjByName = new Map(kjProfiles.map((kj) => [kj.name.toLowerCase(), kj]));

export function getKJBySlug(slug: string): KJProfile | null {
  return kjBySlug.get(slug) ?? null;
}

export function getKJSlugForName(name: string): string | null {
  const profile = kjByName.get(name.toLowerCase());
  return profile?.slug ?? null;
}

export function searchKJs(query: string): KJProfile[] {
  const q = query.toLowerCase();
  return kjProfiles.filter((kj) => kj.name.toLowerCase().includes(q));
}
