export interface KaraokeEvent {
  id: string;
  dayOfWeek: string;
  eventName: string;
  venueName: string;
  address: string;
  city: string;
  state: string;
  neighborhood: string;
  crossStreet: string;
  phone: string;
  dj: string;
  startTime: string;
  endTime: string;
  notes: string;
  image: string | null;
  isPrivateRoom: boolean;
  bookingUrl: string | null;
  website: string | null;
  latitude: number | null;
  longitude: number | null;
}

export const DAY_ORDER = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
  "Bi Monthly Sundays",
  "Every 3rd Monday",
  "Private Room Karaoke",
] as const;

export const karaokeEvents: KaraokeEvent[] = [
  // ─── MONDAY ───
  {
    id: "fusion-east-monday",
    dayOfWeek: "Monday",
    eventName: "Superstar Karaoke",
    venueName: "Fusion East",
    address: "1179 Elton Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "East New York",
    crossStreet: "Vandalia Ave And Egan Street",
    phone: "718-975-5065",
    dj: "DJ Chris Ford",
    startTime: "6:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available, Free Shots For Singers",
    image: "/venues/fusion-east-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://fusioneastny.com/",
    latitude: 40.655973,
    longitude: -73.873590,
  },
  {
    id: "footprints-cafe-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night",
    venueName: "Footprints Cafe",
    address: "5814 Clarendon Road",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Canarsie",
    crossStreet: "East 58th Street And Ralph Avenue",
    phone: "718-451-3181",
    dj: "KJ Anthony Ford",
    startTime: "7:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/footprints-cafe-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://footprintscafenyc.com/",
    latitude: 40.644911,
    longitude: -73.921054,
  },
  {
    id: "saints-scholars-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night",
    venueName: "Saints & Scholars",
    address: "790 Mclean Avenue",
    city: "Yonkers",
    state: "New York",
    neighborhood: "Yonkers",
    crossStreet: "Mc Collum Place And Aqueduct Avenue",
    phone: "914-457-5550",
    dj: "Brooklyn Bill",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available, Kitchen Closes At 9pm",
    image: "/venues/saints-scholars-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.907447,
    longitude: -73.872178,
  },
  {
    id: "native-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night",
    venueName: "Native",
    address: "911 Broadway",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Bushwick",
    crossStreet: "Arion Place And Melrose St",
    phone: "718-747-8288",
    dj: "KJ Gregory Wilson",
    startTime: "6:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available, Kitchen Closes At 9pm",
    image: "/venues/native-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.nativebk.com",
    latitude: 40.697736,
    longitude: -73.936474,
  },
  {
    id: "1683-bar-monday",
    dayOfWeek: "Monday",
    eventName: "Monday Night Karaoke",
    venueName: "1683 Bar & Restaurant",
    address: "401 Sunrise Highway",
    city: "West Islip",
    state: "New York",
    neighborhood: "",
    crossStreet: "",
    phone: "",
    dj: "Buddha's Killa Karaoke",
    startTime: "7:00 PM",
    endTime: "10:30 PM",
    notes: "Food And Drink Specials, Family Friendly, All Ages Welcomed, Kids Menu Available",
    image: "/venues/1683-bar-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.6940,
    longitude: -73.3045,
  },
  {
    id: "island-grill-cafe-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Mondays",
    venueName: "Island Grill Cafe",
    address: "5501 Glenwood Road",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Canarsie",
    crossStreet: "Corner E 55th Street",
    phone: "",
    dj: "DJ Tyrone",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Kitchen Is Open, Try The Rum Punch, Bucket Of Beers Available",
    image: "/venues/island-grill-cafe-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.6418,
    longitude: -73.9040,
  },
  {
    id: "sunset-bar-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Mondays",
    venueName: "Sunset Bar & Restaurant",
    address: "106 W 1st Street",
    city: "Mt Vernon",
    state: "New York",
    neighborhood: "",
    crossStreet: "",
    phone: "",
    dj: "Jaime Hype",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food On Sale By Chef Mel, Drink Specials Available",
    image: "/venues/sunset-bar-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.9101,
    longitude: -73.8379,
  },
  {
    id: "skinny-bar-monday",
    dayOfWeek: "Monday",
    eventName: "Karaoke Night",
    venueName: "The Skinny Bar & Lounge",
    address: "174 Orchard Street",
    city: "New York",
    state: "New York",
    neighborhood: "Lower East Side",
    crossStreet: "",
    phone: "",
    dj: "KJ Troy Kellz",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Free Entry, Doors Open At 7pm, Drinks And Food Available",
    image: "/venues/skinny-bar-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.7213,
    longitude: -73.9888,
  },
  // ─── TUESDAY ───
  {
    id: "pitch-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Pitch",
    address: "774 Flatbush Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Flatbush",
    crossStreet: "Clarkson Ave And Lenox Road",
    phone: "718-313-3100",
    dj: "Various KJ's",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available, Free Shots For Singers",
    image: "/venues/pitch-tuesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.654022,
    longitude: -73.959614,
  },
  {
    id: "flava-2-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Stress Therapy Karaoke Party",
    venueName: "Flava 2",
    address: "8920 Avenue D",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Canarsie",
    crossStreet: "Remsen And East 89th Street",
    phone: "718-975-8512",
    dj: "Stress Therapy Karaoke Party",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://flava2lounge.com/",
    latitude: null,
    longitude: null,
  },
  {
    id: "metropolitan-bar-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Queeraoke",
    venueName: "Metropolitan Bar",
    address: "559 Lorimer Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Williamsburg",
    crossStreet: "Metropolitan Ave And Devoe St",
    phone: "718-599-4444",
    dj: "Miss Katie",
    startTime: "10:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/metropolitan-bar-tuesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.metropolitanbarny.com",
    latitude: 40.713656,
    longitude: -73.949379,
  },
  {
    id: "waterfall-lounge-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Waterfall Lounge",
    address: "4703 Church Ave",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "East Flatbush",
    crossStreet: "Schenectady Ave And East 48th Street",
    phone: "347-365-9318",
    dj: "DJ Dennis",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/waterfall-lounge-monday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.651667,
    longitude: -73.933210,
  },
  {
    id: "barbablu-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Barbablu",
    address: "79 Grand Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Williamsburg",
    crossStreet: "Wythe Avenue And Berry Street",
    phone: "718-388-1999",
    dj: "Dj Plur",
    startTime: "7:00 PM",
    endTime: "10:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://barbablubakenshake.com/",
    latitude: null,
    longitude: null,
  },
  {
    id: "oval-sports-lounge-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "The Oval Sports Bar & Lounge",
    address: "Church Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "East Flatbush",
    crossStreet: "East 42nd Street",
    phone: "",
    dj: "DJ Tye Tye",
    startTime: "8:00 PM",
    endTime: "2:00 AM",
    notes: "Free All Night, Drinks On You",
    image: "/venues/oval-sports-lounge-tuesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.6505,
    longitude: -73.9262,
  },
  {
    id: "harlem-nights-bar-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Tuesdays",
    venueName: "Harlem Nights Bar",
    address: "2361 Adam Clayton Powell Jr Blvd",
    city: "New York",
    state: "New York",
    neighborhood: "Harlem",
    crossStreet: "",
    phone: "",
    dj: "Mo The Vet",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Karaoke Junkees, Food And Drinks Available",
    image: "/venues/harlem-nights-bar-tuesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.8197,
    longitude: -73.9403,
  },
  {
    id: "blu-seafood-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "Karaoke Night",
    venueName: "Blu Seafood Restaurant",
    address: "222-02 Merrick Blvd",
    city: "Queens",
    state: "New York",
    neighborhood: "Springfield Gardens",
    crossStreet: "",
    phone: "",
    dj: "DJ Les",
    startTime: "7:00 PM",
    endTime: "12:00 AM",
    notes: "Free Shots For Singers",
    image: "/venues/blu-seafood-tuesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.6695,
    longitude: -73.7355,
  },
  {
    id: "mos-bar-tuesday",
    dayOfWeek: "Tuesday",
    eventName: "So Fresh So Clean Karaoke",
    venueName: "Mo's Bar And Lounge",
    address: "80 Lafayette Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Fort Greene",
    crossStreet: "",
    phone: "",
    dj: "Lamont",
    startTime: "7:00 PM",
    endTime: "11:00 PM",
    notes: "Happy Hour Ends At 7pm, Arrive Early For Choice Seating",
    image: "/venues/mos-bar-tuesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.6886,
    longitude: -73.9751,
  },
  // ─── WEDNESDAY ───
  {
    id: "patrick-steakhouse-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Patrick Steakhouse",
    address: "227 Rogers Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Crown Heights",
    crossStreet: "Union Street And President Street",
    phone: "347-789-9976",
    dj: "DJ Ron Entertainment",
    startTime: "5:00 PM",
    endTime: "10:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/patrick-steakhouse-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://patricksteakhouse.com/",
    latitude: 40.668518,
    longitude: -73.953335,
  },
  {
    id: "poseidon-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Happy Hour Karaoke",
    venueName: "Poseidon",
    address: "279 Flatbush Ave",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Prospect Heights",
    crossStreet: "St Mark's Ave And Prosplect Place",
    phone: "347-365-7637",
    dj: "DJ M-Tunez",
    startTime: "7:00 PM",
    endTime: "2:00 AM",
    notes: "Happy Hour All Night",
    image: "/venues/poseidon-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.679511,
    longitude: -73.974062,
  },
  {
    id: "irish-american-pub-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Irish American Pub",
    address: "17 John Street",
    city: "New York",
    state: "New York",
    neighborhood: "Financial District",
    crossStreet: "Nassau Street And Broadway",
    phone: "347-365-7637",
    dj: "DJ Plur",
    startTime: "6:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.irishamericanpubnyc.com/",
    latitude: 40.709948,
    longitude: -74.008893,
  },
  {
    id: "buck-it-sports-latin-grill-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Buck It Sports & Latin Grill",
    address: "1039 Surf Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Coney Island",
    crossStreet: "West 12th St & West 10th St",
    phone: "347-347-2157",
    dj: "DJ Oscar De La Paz",
    startTime: "7:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/buck-it-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://buck-it-bar.com/",
    latitude: 40.575548,
    longitude: -73.978694,
  },
  {
    id: "my-place-tavern-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "My Place Tavern",
    address: "990 Middle Country Rd",
    city: "Selden",
    state: "New York",
    neighborhood: "Brookhaven",
    crossStreet: "Off Of College Road",
    phone: "631-846-9091",
    dj: "KJ Road Dog Tony",
    startTime: "7:30 PM",
    endTime: "11:30 PM",
    notes: "Every Song Gets A Spin On The Prize Wheel",
    image: "/venues/my-place-tavern-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.863850,
    longitude: -73.047384,
  },
  {
    id: "gt-kingston-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Open Mic Karaoke",
    venueName: "GT Kingston",
    address: "114-45 Lefferts Blvd",
    city: "Queens",
    state: "New York",
    neighborhood: "South Ozone Park",
    crossStreet: "Linden Blvd And 115th Ave",
    phone: "718-848-6006",
    dj: "Dj Denis",
    startTime: "8:00 PM",
    endTime: "4:00 AM",
    notes: "Free Fried Fish & Festival",
    image: "/venues/gt-kingston-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.677980,
    longitude: -73.820041,
  },
  {
    id: "lagos-times-square-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Lagos Times Square",
    address: "727 7th Avenue",
    city: "Manhattan",
    state: "New York",
    neighborhood: "Theater District",
    crossStreet: "West 48th Street And West 49th Street",
    phone: "212-281-0500",
    dj: "Various KJ's",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/lagos-times-square-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.lagosnyc.com/",
    latitude: 40.760253,
    longitude: -73.983792,
  },
  {
    id: "mc-shanes-pub-restaurant-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Mc Shane's Pub & Restaurant",
    address: "123 N Main St",
    city: "Port Chester",
    state: "New York",
    neighborhood: "Port Chester",
    crossStreet: "Adee St And Willett Ave",
    phone: "914-937-7800",
    dj: "Brooklyn Bill",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/mc-shane-s-pub-restaurant-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "http://www.mcshanesportchester.com/",
    latitude: 41.002549,
    longitude: -73.661653,
  },
  {
    id: "alligator-lounge-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Alligator Lounge",
    address: "600 Metropolitan Ave",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Williamsburg",
    crossStreet: "Lorimer Street And Leonard Street",
    phone: "718-599-4440",
    dj: "Various Kj's",
    startTime: "11:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: "http://www.alligatorloungebrooklyn.com/",
    latitude: null,
    longitude: null,
  },
  {
    id: "ocho-rios-wednesday",
    dayOfWeek: "Wednesday",
    eventName: "Karaoke Night",
    venueName: "Ocho Rios Seafood & Lounge",
    address: "1810 Flatbush Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Flatlands",
    crossStreet: "Avenue K",
    phone: "",
    dj: "DJ Cindy & DJ Suppamixx",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food On The House, Bucket Beers 6 For $25",
    image: "/venues/ocho-rios-wednesday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.6188,
    longitude: -73.9470,
  },
  // ─── THURSDAY ───
  {
    id: "ocean-prime-thursday",
    dayOfWeek: "Thursday",
    eventName: "Open Acoustic Jam",
    venueName: "Ocean Prime",
    address: "64-14 Flushing Avenue",
    city: "Maspeth",
    state: "New York",
    neighborhood: "Maspeth",
    crossStreet: "64th Street And 65th Street",
    phone: "718-326-3707",
    dj: "Dead Roses Productions",
    startTime: "6:00 PM",
    endTime: "10:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/ocean-prime-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.722684,
    longitude: -73.901299,
  },
  {
    id: "fusion-east-thursday",
    dayOfWeek: "Thursday",
    eventName: "Superstar Karaoke/LadiesNight",
    venueName: "Fusion East",
    address: "1179 Elton St",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "East New York",
    crossStreet: "Vandalia Ave And Egan Street",
    phone: "718-326-3707",
    dj: "Dj Chris Forde",
    startTime: "6:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available, Free Shots For Singers, Ladies Free Shot Everytime They Sing",
    image: "/venues/fusion-east-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://fusioneastny.com/",
    latitude: 40.655973,
    longitude: -73.873590,
  },
  {
    id: "murfs-backstreet-tavern-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Murf's Backstreet Tavern",
    address: "64 Division Street",
    city: "Sag Harbor",
    state: "New York",
    neighborhood: "Southampton",
    crossStreet: "Rector Street And Cross Street",
    phone: "631-899-3575",
    dj: "KJ John Barrett",
    startTime: "6:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/murf-s-backstreet-tavern-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 41.000122,
    longitude: -72.294049,
  },
  {
    id: "irish-american-pub-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Irish American Pub",
    address: "17 John Street",
    city: "New York",
    state: "New York",
    neighborhood: "Financial District",
    crossStreet: "Nassau Street And Broadway",
    phone: "347-365-7637",
    dj: "DJ Plur",
    startTime: "6:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.irishamericanpubnyc.com/",
    latitude: 40.709948,
    longitude: -74.008893,
  },
  {
    id: "arirang-hibachi-steakhouse-thursday",
    dayOfWeek: "Thursday",
    eventName: "Kimono Karaoke",
    venueName: "Arirang Hibachi Steakhouse",
    address: "8812-14 4th Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Bay Ridge",
    crossStreet: "88th Street And 89th Street",
    phone: "718-808-6105",
    dj: "Kimono Karaoke",
    startTime: "6:30 PM",
    endTime: "Late",
    notes: "Food And Drinks Available, Free Sake Shot For First Time Singers",
    image: "/venues/the-samurai-lounge-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.partyonthegrill.com/location/arirang-steakhouse-brooklyn-ny/",
    latitude: 40.621141,
    longitude: -74.029109,
  },
  {
    id: "deja-vu-haitian-restaurant-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Deja Vu Haitian Restaurant",
    address: "301 West 151 Street",
    city: "Harlem",
    state: "New York",
    neighborhood: "Central Harlem",
    crossStreet: "Bradhurst Avenue And Frederick Douglas Boulevard",
    phone: "718-737-3634",
    dj: "Queen Tashabee",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/deja-vu-haitian-restaurant-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.826707,
    longitude: -73.939177,
  },
  {
    id: "prohibition-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Prohibition",
    address: "109 Front Street",
    city: "Massapequa Park",
    state: "New York",
    neighborhood: "Massapequa Park",
    crossStreet: "7th Avenue And Park Boulevard",
    phone: "516-809-9223",
    dj: "Dj Brooke",
    startTime: "8:30 PM",
    endTime: "Late",
    notes: "Food And Drinks Available",
    image: "/venues/prohibition-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.678040,
    longitude: -73.455571,
  },
  {
    id: "curly-wolf-saloon-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Curly Wolf Saloon",
    address: "4116 Hylan Boulevard 2nd Floor",
    city: "Staten Island",
    state: "New York",
    neighborhood: "Great Kills",
    crossStreet: "Glover Street And Goodall Street",
    phone: "718-227-0027",
    dj: "Dj Frankie J",
    startTime: "9:00 PM",
    endTime: "12:00 AM",
    notes: "Liquid Courage Poured By Angela",
    image: "/venues/curly-wolf-saloon-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.facebook.com/CurlyWolfSaloon/",
    latitude: 40.539498,
    longitude: -74.148280,
  },
  {
    id: "pitants-sports-bar-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Pitants Sports Bar",
    address: "502 East 95th Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Brownsville",
    crossStreet: "Church Ave And Willmohr Street",
    phone: "",
    dj: "Stress Therapy Karaoke Party",
    startTime: "10:00 PM",
    endTime: "3:00 AM",
    notes: "Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: null,
    longitude: null,
  },
  {
    id: "island-suite-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Island Suite",
    address: "4112 Avenue D",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "East Flatbush",
    crossStreet: "Albany And East 42nd Street",
    phone: "",
    dj: "DJ Les",
    startTime: "10:00 PM",
    endTime: "3:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: null,
    longitude: null,
  },
  {
    id: "the-noon-inn-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "The Noon Inn",
    address: "382A East Meadow Avenue",
    city: "East Meadow",
    state: "New York",
    neighborhood: "",
    crossStreet: "Prospect Ave And Franklin Ave",
    phone: "516-502-0803",
    dj: "Kara Okee",
    startTime: "8:30 PM",
    endTime: "12:30 AM",
    notes: "Food And Drinks Available",
    image: "/venues/the-noon-inn-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.714521,
    longitude: -73.559895,
  },
  {
    id: "rollin-greens-thursday",
    dayOfWeek: "Thursday",
    eventName: "Karaoke Night",
    venueName: "Rollin Greens",
    address: "247-77 Jericho Turnpike",
    city: "Bellrose",
    state: "New York",
    neighborhood: "Floral Park",
    crossStreet: "Commonwealth Boulevard And 91st Avenue",
    phone: "718-343-3313",
    dj: "KJ Morgan",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/rollin-greens-thursday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.725976,
    longitude: -73.718989,
  },
  // ─── FRIDAY ───
  {
    id: "shannon-pot-2-friday",
    dayOfWeek: "Friday",
    eventName: "Friday Night Karaoke",
    venueName: "Shannon Pot 2",
    address: "10-50 44th Drive",
    city: "Long Island City",
    state: "New York",
    neighborhood: "Hunters Point",
    crossStreet: "10th And 11th Street",
    phone: "917-396-1828",
    dj: "DJ Vince",
    startTime: "8:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/shannon-pot-2-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.748679,
    longitude: -73.950633,
  },
  {
    id: "ocean-prime-friday",
    dayOfWeek: "Friday",
    eventName: "Friday Night Karaoke",
    venueName: "Ocean Prime",
    address: "64-14 Flushing Ave",
    city: "Maspeth",
    state: "New York",
    neighborhood: "Maspeth",
    crossStreet: "64th And 65th Street",
    phone: "718-326-3707",
    dj: "Karaoke Chris",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/ocean-prime-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.722684,
    longitude: -73.901299,
  },
  {
    id: "its-about-time-cocktail-lounge-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "It's About Time Cocktail Lounge",
    address: "706 Main Street",
    city: "South Farmingdale",
    state: "New York",
    neighborhood: "South Farmingdale",
    crossStreet: "Yoakum Ave And Fallwood Parkway",
    phone: "516-586-6690",
    dj: "KJ Road Dog Tony",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available, Rotating Specials",
    image: "/venues/it-s-about-time-cocktail-lounge-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.723205,
    longitude: -73.441982,
  },
  {
    id: "good-company-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "Good Company",
    address: "253-32 Northern Boulevard",
    city: "Queens",
    state: "New York",
    neighborhood: "Little Neck",
    crossStreet: "Westmoreland Street And Little Neck Parkway",
    phone: "718-428-0987",
    dj: "KJ Morgan",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/good-company-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.771405,
    longitude: -73.734779,
  },
  {
    id: "allans-bakery-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Friday's",
    venueName: "Allan's Bakery",
    address: "1107 Nostrand Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Prospect Lefferts Gardens",
    crossStreet: "Maple Street And Midwood Street",
    phone: "718-774-7892",
    dj: "Stress Therapy Karaoke Party",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/allans-bakery-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.allansbakery.com/",
    latitude: 40.660641,
    longitude: -73.950549,
  },
  {
    id: "american-legion-hall-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke And Live Music",
    venueName: "American Legion Hall",
    address: "1130 East 92nd Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Canarsie",
    crossStreet: "Conklin Avenue And Glenwood Road",
    phone: "917-903-0334",
    dj: "Technic Music Mix",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/american-legion-hall-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.641784,
    longitude: -73.905513,
  },
  {
    id: "woodzy-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "Woodzy",
    address: "1133 Clarkson Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Brownsville",
    crossStreet: "Rockaway Parkway And East 96th Street",
    phone: "718-552-2687",
    dj: "DJ Hailes Costello",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/woodzy-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://woodzzybarandrestaurant.com/",
    latitude: 40.660691,
    longitude: -73.920883,
  },
  {
    id: "essence-bar-grill-friday",
    dayOfWeek: "Friday",
    eventName: "Superstar Karaoke",
    venueName: "Essence Bar & Grill",
    address: "1662 Atlantic Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Crown Heights",
    crossStreet: "Troy Avenue And Schnectady Avenue",
    phone: "718-467-3300",
    dj: "DJ Chris Ford",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available, Free Shot For Singers",
    image: "/venues/essence-bar-grill-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://essencebar.com/",
    latitude: 40.677572,
    longitude: -73.935788,
  },
  {
    id: "irish-american-pub-friday",
    dayOfWeek: "Friday",
    eventName: "Karaoke Night",
    venueName: "Irish American Pub",
    address: "17 John Street",
    city: "New York",
    state: "New York",
    neighborhood: "Financial District",
    crossStreet: "Nassau Street And Broadway",
    phone: "347-365-7637",
    dj: "DJ Plur",
    startTime: "6:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.irishamericanpubnyc.com/",
    latitude: 40.709948,
    longitude: -74.008893,
  },
  {
    id: "instant-reply-sports-bar-friday",
    dayOfWeek: "Friday",
    eventName: "Friday Night Karaoke",
    venueName: "Instant Reply Sports Bar",
    address: "282 East Jericho Turnpike",
    city: "Huntington Station",
    state: "New York",
    neighborhood: "South Huntington",
    crossStreet: "Goeller Ave & Barkers Lane",
    phone: "631-673-6161",
    dj: "DJ Rizzo",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/instant-reply-sports-bar-friday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: null,
    longitude: null,
  },
  // ─── SATURDAY ───
  {
    id: "la-cocina-boriqua-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Party",
    venueName: "La Cocina Boriqua",
    address: "2245 Westchester Avenue",
    city: "Bronx",
    state: "New York",
    neighborhood: "Belmont",
    crossStreet: "Glebe Avenue And Castle Hill Avenue",
    phone: "347-281-5375",
    dj: "DJ Nap",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Two Drink Minimum",
    image: "/venues/la-cocina-boriqua-saturday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.834388,
    longitude: -73.850364,
  },
  {
    id: "whisky-reds-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Night",
    venueName: "Whisky Red's",
    address: "2552 Hempstead Turnpike",
    city: "East Meadow",
    state: "New York",
    neighborhood: "East Meadow",
    crossStreet: "Taylor Avenue And Newbridge Road",
    phone: "516-605-0099",
    dj: "Kara Okee",
    startTime: "9:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/whisky-red-s-saturday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://whiskeyredspub.com/",
    latitude: 40.724036,
    longitude: -73.540765,
  },
  {
    id: "moonlight-pub-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Night",
    venueName: "Moonlight Pub",
    address: "247-77 Jericho Turnpike",
    city: "Bellrose",
    state: "New York",
    neighborhood: "Bellrose",
    crossStreet: "Commonwealth Boulevard And 91st Avenue",
    phone: "718-343-3313",
    dj: "KJ Morgan",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/moonlight-pub-saturday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.725976,
    longitude: -73.718989,
  },
  {
    id: "irish-american-pub-saturday",
    dayOfWeek: "Saturday",
    eventName: "Karaoke Saturday",
    venueName: "Irish American Pub",
    address: "17 John Street",
    city: "Manhattan",
    state: "New York",
    neighborhood: "Financial District",
    crossStreet: "Nassau Street And Broadway",
    phone: "646-414-6223",
    dj: "DJ Sri",
    startTime: "9:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/irish-american-pub-saturday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.irishamericanpubnyc.com/",
    latitude: 40.709948,
    longitude: -74.008893,
  },
  {
    id: "c-list-cocktail-bar-saturday",
    dayOfWeek: "Saturday",
    eventName: "Superstar Karaoke",
    venueName: "C-List Cocktail Bar",
    address: "835 Franklin Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Crown Heights",
    crossStreet: "Union Street",
    phone: "",
    dj: "VDJ Chris Forde",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/c-list-cocktail-bar-saturday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.6709,
    longitude: -73.9565,
  },
  // ─── SUNDAY ───
  {
    id: "333-lounge-and-restaurant-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "333 Lounge And Restaurant",
    address: "333 Flatbush Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Prospect Heights",
    crossStreet: "Park Place And Prospect Place",
    phone: "718-399-8008",
    dj: "KJ Anthony Ford",
    startTime: "4:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/333-lounge-and-restaurant-sunday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.333lounge.com/",
    latitude: 40.677822,
    longitude: -73.972842,
  },
  {
    id: "pitants-sports-bar-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "Pitants Sports Bar",
    address: "502 East 95th Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Brownsville",
    crossStreet: "Church Ave And Willmohr Street",
    phone: "",
    dj: "Dj Denis",
    startTime: "10:00 PM",
    endTime: "3:00 AM",
    notes: "Drinks Available",
    image: "/venues/pitants-sports-bar-sunday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: null,
    longitude: null,
  },
  {
    id: "la-mode-bk-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "La Mode BK",
    address: "1401 Bedford Ave",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Crown Heights",
    crossStreet: "Prospect Place And St Marks Ave",
    phone: "718-316-9100",
    dj: "DJ Hailes Costello",
    startTime: "2:00 PM",
    endTime: "6:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/la-mode-bk-sunday.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://lamodebk.com/",
    latitude: null,
    longitude: null,
  },
  {
    id: "the-coal-pot-sunday",
    dayOfWeek: "Sunday",
    eventName: "Karaoke Night",
    venueName: "The Coal Pot",
    address: "1466 St John's Place",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Crown Heights",
    crossStreet: "Utica Ave And Rochester Ave",
    phone: "347-404-7705",
    dj: "Stress Therapy Karaoke Party",
    startTime: "7:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: null,
    longitude: null,
  },
  {
    id: "midwood-flats-sunday",
    dayOfWeek: "Sunday",
    eventName: "Drag Queen Karaoke",
    venueName: "Midwood Flats",
    address: "577 Flatbush Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "East Flatbush",
    crossStreet: "Midwood Street And Maple Street",
    phone: "347-404-7705",
    dj: "Miss Behave",
    startTime: "9:00 PM",
    endTime: "1:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://midwoodflats.com/",
    latitude: null,
    longitude: null,
  },
  // ─── BI MONTHLY SUNDAYS ───
  {
    id: "lilahs-bar-and-grill-bi-monthly-sundays",
    dayOfWeek: "Bi Monthly Sundays",
    eventName: "Karaoke Night",
    venueName: "Lilah's Bar And Grill",
    address: "33 Main Street",
    city: "East Rockaway",
    state: "New York",
    neighborhood: "East Rockaway",
    crossStreet: "Cammerer Avenue And Front Street",
    phone: "516-284-7397",
    dj: "KJ Road Dog Tony",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/lilah-s-bar-and-grill-bi-monthly-sundays.jpg",
    isPrivateRoom: false,
    bookingUrl: null,
    website: null,
    latitude: 40.640022,
    longitude: -73.661935,
  },
  // ─── EVERY 3RD MONDAY ───
  {
    id: "whoopsie-daisy-bar-every-3rd-monday",
    dayOfWeek: "Every 3rd Monday",
    eventName: "Kickback Karaoke",
    venueName: "Whoopsie Daisy Bar",
    address: "225 Rogers Avenue",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Crown Heights",
    crossStreet: "Union Street And President Street",
    phone: "347-365-4193",
    dj: "Miss Behave",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: false,
    bookingUrl: null,
    website: "https://www.whoopsiedaisybk.com/",
    latitude: null,
    longitude: null,
  },
  // ─── PRIVATE ROOM KARAOKE ───
  {
    id: "sing-sing-karaoke-avenue-a",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Sing Sing Karaoke",
    address: "81 Avenue A",
    city: "New York",
    state: "New York",
    neighborhood: "East Village",
    crossStreet: "East 5th & East 6th St",
    phone: "212-674-0700",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/sing-sing-avenue-a.jpg",
    isPrivateRoom: true,
    bookingUrl: null,
    website: "https://www.singsingavea.com/",
    latitude: 40.725231,
    longitude: -73.984221,
  },
  {
    id: "sing-sing-karaoke-st-marks",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Sing Sing Karaoke",
    address: "9 St Marks Place",
    city: "New York",
    state: "New York",
    neighborhood: "West Village",
    crossStreet: "2nd And 3rd Ave",
    phone: "212-387-7800",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    notes: "Food And Drinks Available",
    image: "/venues/sing-sing-st-marks.jpg",
    isPrivateRoom: true,
    bookingUrl: null,
    website: "https://www.karaokesingsing.com/",
    latitude: 40.729375,
    longitude: -73.989333,
  },
  {
    id: "boho-karaoke-west-4th",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Boho Karaoke",
    address: "186 West 4th Street",
    city: "New York",
    state: "New York",
    neighborhood: "Washington Square Village",
    crossStreet: "Barrow St And Jones Street",
    phone: "212-255-0011",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "4:00 PM",
    endTime: "4:00 AM",
    notes: "Food And Drinks Available",
    image: "/venues/boho-karaoke.jpg",
    isPrivateRoom: true,
    bookingUrl: null,
    website: "https://www.west4karaoke.com/",
    latitude: 40.732476,
    longitude: -74.001893,
  },
  {
    id: "boho-karaoke-orchard",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Boho Karaoke",
    address: "152 Orchard Street",
    city: "New York",
    state: "New York",
    neighborhood: "China Town",
    crossStreet: "Rivington And Stanton Street",
    phone: "212-777-0102",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "4:00 PM",
    endTime: "4:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: "https://www.karaokeboho.com/",
    latitude: null,
    longitude: null,
  },
  {
    id: "aux-karaoke-private-room-karaoke",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Aux Karaoke",
    address: "2142 Fulton Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Bedstuy",
    crossStreet: "Rockaway Avenue And Thomas S Boyland Street",
    phone: "718-218-3348",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "5:00 PM",
    endTime: "12:00 AM",
    notes: "Drinks Only",
    image: "/venues/aux-karaoke.jpg",
    isPrivateRoom: true,
    bookingUrl: null,
    website: "https://www.auxkaraokebox.com",
    latitude: 40.678252,
    longitude: -73.911339,
  },
  {
    id: "anytime-karaoke-private-room",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Anytime Karaoke",
    address: "23 W 32nd Street",
    city: "New York",
    state: "New York",
    neighborhood: "Koreatown",
    crossStreet: "5th And 6th Avenue",
    phone: "646-590-4703",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "5:00 PM",
    endTime: "3:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: "https://www.karaokeanytime.com/",
    latitude: null,
    longitude: null,
  },
  {
    id: "rpm-underground-private-room",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "RPM Underground",
    address: "246 W 54th Street",
    city: "New York",
    state: "New York",
    neighborhood: "Midtown",
    crossStreet: "8th Avenue And Broadway",
    phone: "",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "10:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available, Till 4am On Fridays And Saturdays",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: "http://rpmunderground.us/",
    latitude: null,
    longitude: null,
  },
  {
    id: "ms-kims-private-room",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Ms Kims",
    address: "6 West 28th Street Floor 2",
    city: "New York",
    state: "New York",
    neighborhood: "Nomad",
    crossStreet: "Broadway And 5th Avenue",
    phone: "929-505-3368",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "6:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available, Till 2am On Fridays And Saturdays",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: "https://www.mskims.co/",
    latitude: null,
    longitude: null,
  },
  {
    id: "karaoke-shout-private-room",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "Karaoke Shout",
    address: "32-46 Steinway Street",
    city: "Astoria",
    state: "New York",
    neighborhood: "Astoria",
    crossStreet: "Broadway And 34th Avenue",
    phone: "718-569-0080",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "5:00 PM",
    endTime: "2:00 AM",
    notes: "Food And Drinks Available, Till 4am On Fridays And Saturdays",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: "http://www.karaokeshout.com/",
    latitude: null,
    longitude: null,
  },
  {
    id: "233-starr-karaoke-private-room",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "233 Starr Karaoke And Eats",
    address: "233 Starr Street",
    city: "Brooklyn",
    state: "New York",
    neighborhood: "Bushwick",
    crossStreet: "Wyckoff Ave And Irving Ave",
    phone: "929-210-8687",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "4:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available, Till 2am On Fridays And Saturdays",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: "http://www.233starrkaraoke.com/",
    latitude: null,
    longitude: null,
  },
  {
    id: "singsing-karaoke-astoria-private-room",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "SingSing Karaoke Bar And Chicken",
    address: "25-30 Broadway",
    city: "Astoria",
    state: "New York",
    neighborhood: "Astoria",
    crossStreet: "Crescent And 29th Street",
    phone: "929-210-8687",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "4:00 PM",
    endTime: "12:00 AM",
    notes: "Food And Drinks Available, Till 2am On Fridays And Saturdays",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: "https://www.singsingastoria.com/",
    latitude: null,
    longitude: null,
  },
  {
    id: "101-ktv-bar-lounge-private-room",
    dayOfWeek: "Private Room Karaoke",
    eventName: "Karaoke",
    venueName: "101 KTV Bar Lounge",
    address: "135-25 Northern Boulevard",
    city: "Flushing",
    state: "New York",
    neighborhood: "Flushing",
    crossStreet: "Prince Street And Farrington Street",
    phone: "929-520-1011",
    dj: "Private Rooms And Open Karaoke Bar",
    startTime: "2:00 PM",
    endTime: "4:00 AM",
    notes: "Food And Drinks Available",
    image: null,
    isPrivateRoom: true,
    bookingUrl: null,
    website: "https://101ktv.my.canva.site/",
    latitude: null,
    longitude: null,
  },
];

// Helper: get events grouped by day, or for a specific day
export function getEventsByDay(): Record<string, KaraokeEvent[]>;
export function getEventsByDay(day: string): KaraokeEvent[];
export function getEventsByDay(day?: string): Record<string, KaraokeEvent[]> | KaraokeEvent[] {
  if (day) return karaokeEvents.filter((e) => e.dayOfWeek === day);
  const grouped: Record<string, KaraokeEvent[]> = {};
  for (const event of karaokeEvents) {
    if (!grouped[event.dayOfWeek]) grouped[event.dayOfWeek] = [];
    grouped[event.dayOfWeek].push(event);
  }
  return grouped;
}

// Helper: venues derived from events (unique by name)
export const venues = karaokeEvents.reduce<
  Array<{
    id: string;
    name: string;
    address: string;
    neighborhood: string;
    city: string;
    state: string;
    image: string | null;
    isPrivateRoom: boolean;
    latitude: number | null;
    longitude: number | null;
  }>
>((acc, event) => {
  if (!acc.find((v) => v.name === event.venueName)) {
    acc.push({
      id: event.id,
      name: event.venueName,
      address: event.address,
      neighborhood: event.neighborhood,
      city: event.city,
      state: event.state,
      image: event.image,
      isPrivateRoom: event.isPrivateRoom,
      latitude: event.latitude,
      longitude: event.longitude,
    });
  }
  return acc;
}, []);

// ─── KJ DIRECTORY ───

// Generic DJ names that shouldn't get their own profile
const GENERIC_DJ_NAMES = new Set([
  "various kj's",
  "various kj's",
  "rotating dj's",
  "rotating djs",
  "open",
  "private rooms and open karaoke bar",
  "",
]);

function generateKJSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export interface KJProfile {
  slug: string;
  name: string;
  events: Array<{
    venueName: string;
    venueId: string;
    dayOfWeek: string;
    startTime: string;
    endTime: string;
    eventName: string;
    image: string | null;
    neighborhood: string;
    city: string;
  }>;
  venueCount: number;
}

// Unique KJs derived from events (filter out generic names)
export const kjs: KJProfile[] = (() => {
  const map = new Map<string, KJProfile>();

  for (const event of karaokeEvents) {
    const djName = event.dj.trim();
    if (GENERIC_DJ_NAMES.has(djName.toLowerCase())) continue;

    const slug = generateKJSlug(djName);
    if (!slug) continue;

    const existing = map.get(slug);
    if (existing) {
      existing.events.push({
        venueName: event.venueName,
        venueId: event.id,
        dayOfWeek: event.dayOfWeek,
        startTime: event.startTime,
        endTime: event.endTime,
        eventName: event.eventName,
        image: event.image,
        neighborhood: event.neighborhood,
        city: event.city,
      });
      // Update venue count (unique venues)
      existing.venueCount = new Set(existing.events.map((e) => e.venueName)).size;
    } else {
      map.set(slug, {
        slug,
        name: djName,
        events: [
          {
            venueName: event.venueName,
            venueId: event.id,
            dayOfWeek: event.dayOfWeek,
            startTime: event.startTime,
            endTime: event.endTime,
            eventName: event.eventName,
            image: event.image,
            neighborhood: event.neighborhood,
            city: event.city,
          },
        ],
        venueCount: 1,
      });
    }
  }

  return Array.from(map.values()).sort((a, b) => a.name.localeCompare(b.name));
})();

export function getKJBySlug(slug: string): KJProfile | undefined {
  return kjs.find((kj) => kj.slug === slug);
}

export function searchKJs(query: string): KJProfile[] {
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];
  return kjs.filter((kj) => kj.name.toLowerCase().includes(q));
}

export function getKJSlugForName(djName: string): string | null {
  const name = djName.trim();
  if (GENERIC_DJ_NAMES.has(name.toLowerCase())) return null;
  const slug = generateKJSlug(name);
  return slug || null;
}

// Placeholder reviews (to be replaced by Supabase)
export const reviews: Array<{
  id: string;
  venueId: string;
  userName: string;
  rating: number;
  text: string;
  date: string;
}> = [];

// Song search demo data (used by /search page)
export const songSearchResults = [
  {
    song: "Don't Stop Believin'",
    artist: "Journey",
    venues: [
      { name: "Sing Sing Karaoke", distance: "0.3 mi", available: true, waitTime: "~15 min wait", special: "Happy Hour till 8 PM" },
      { name: "Boho Karaoke", distance: "0.5 mi", available: true, waitTime: null, special: null },
      { name: "Aux Karaoke", distance: "1.2 mi", available: false, waitTime: null, special: "2-for-1 Drinks" },
    ],
  },
];
