import { NextResponse } from "next/server";
import { createClient as createServerClient } from "@/lib/supabase/server";
import { createClient } from "@supabase/supabase-js";

export const maxDuration = 300; // 5 minutes max for batch processing

export async function POST() {
  // Verify admin
  const serverSupabase = await createServerClient();
  const {
    data: { user },
  } = await serverSupabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ success: false, message: "Not authenticated" }, { status: 401 });
  }

  const { data: profile } = await serverSupabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single();

  if (!profile || profile.role !== "admin") {
    return NextResponse.json({ success: false, message: "Admin access required" }, { status: 403 });
  }

  const webhookUrl = process.env.N8N_WEBHOOK_URL;
  if (!webhookUrl) {
    return NextResponse.json({
      success: false,
      message: "N8N_WEBHOOK_URL not configured. Cannot generate flyers.",
    });
  }

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  // Find all events without a flyer_url
  const { data: events, error } = await supabase
    .from("venue_events")
    .select("id, venue_id, day_of_week, event_name, dj, start_time, end_time, notes, venues(name, address, city, state)")
    .is("flyer_url", null)
    .eq("is_active", true)
    .order("day_of_week");

  if (error || !events) {
    return NextResponse.json({
      success: false,
      message: "Failed to fetch events: " + (error?.message || "unknown"),
    });
  }

  if (events.length === 0) {
    return NextResponse.json({
      success: true,
      message: "All active events already have flyers!",
      generated: 0,
      failed: 0,
    });
  }

  let generated = 0;
  let failed = 0;
  const errors: string[] = [];

  // Process in batches of 3 to avoid overwhelming n8n
  const BATCH_SIZE = 3;
  for (let i = 0; i < events.length; i += BATCH_SIZE) {
    const batch = events.slice(i, i + BATCH_SIZE);

    const results = await Promise.allSettled(
      batch.map(async (event) => {
        const venue = event.venues as unknown as {
          name: string;
          address: string;
          city: string;
          state: string;
        } | null;

        const venueName = venue?.name || "Karaoke Venue";
        const venueAddress = venue?.address || "";

        // Build a minimal flyer request for n8n
        const payload = {
          eventName: event.event_name || "Karaoke Night",
          venueName,
          venueAddress: `${venueAddress}${venue?.city ? `, ${venue.city}` : ""}`,
          eventDate: event.day_of_week || "Weekly",
          startTime: event.start_time || "9:00 PM",
          endTime: event.end_time || "",
          coverCharge: "",
          theme: "Open Mic Karaoke",
          moodDescription: `${event.event_name || "Karaoke"} at ${venueName}`,
          dressCode: "",
          specialFeatures: [],
          drinkSpecials: "",
          foodDeals: "",
          prizes: "",
          promoText: event.dj ? `Hosted by ${event.dj}` : "",
          venueId: event.venue_id,
          userId: user.id,
          autoGenerated: true,
          generatedAt: new Date().toISOString(),
        };

        try {
          const res = await fetch(webhookUrl, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          });

          if (!res.ok) {
            throw new Error(`n8n returned ${res.status}`);
          }

          const result = await res.json();

          if (!result.success || (!result.imageUrl && !result.imageBase64)) {
            throw new Error(result.error || "No image returned");
          }

          // Get the image URL (prefer direct URL over base64)
          let imageUrl = result.imageUrl;

          // If only base64 was returned, upload it to Supabase storage
          if (!imageUrl && result.imageBase64) {
            const fileName = `auto-flyers/${event.id}-${Date.now()}.webp`;
            const buffer = Buffer.from(result.imageBase64, "base64");

            const { error: uploadError } = await supabase.storage
              .from("flyer-uploads")
              .upload(fileName, buffer, {
                contentType: "image/webp",
                upsert: true,
              });

            if (uploadError) throw new Error("Upload failed: " + uploadError.message);

            const { data: urlData } = supabase.storage
              .from("flyer-uploads")
              .getPublicUrl(fileName);

            imageUrl = urlData.publicUrl;
          }

          // Update the event's flyer_url
          const { error: updateError } = await supabase
            .from("venue_events")
            .update({ flyer_url: imageUrl })
            .eq("id", event.id);

          if (updateError) throw new Error("DB update failed: " + updateError.message);

          return { eventId: event.id, venueName, success: true };
        } catch (err: any) {
          throw new Error(`${venueName} — ${event.event_name}: ${err.message}`);
        }
      })
    );

    for (const result of results) {
      if (result.status === "fulfilled") {
        generated++;
      } else {
        failed++;
        errors.push(result.reason?.message || "Unknown error");
      }
    }

    // Small delay between batches to avoid rate limits
    if (i + BATCH_SIZE < events.length) {
      await new Promise((resolve) => setTimeout(resolve, 2000));
    }
  }

  return NextResponse.json({
    success: true,
    message: `Generated ${generated} flyers. ${failed > 0 ? `${failed} failed.` : "All succeeded!"}`,
    generated,
    failed,
    total: events.length,
    errors: errors.length > 0 ? errors.slice(0, 10) : undefined,
  });
}
